// Real MSME Schemes Data for India
// Comprehensive Database - 2024-2026
// Total: 150+ Schemes across Central, State, and Sectoral categories

export const CENTRAL_SCHEMES = [
  // ========== MUDRA SCHEMES ==========
  {
    name: 'PM Mudra Yojana - Shishu',
    slug: 'pm-mudra-yojana-shishu',
    shortDescription: 'Collateral-free loans up to ₹50,000 for micro enterprises',
    description: 'PM Mudra Yojana is a flagship scheme launched by the Government of India to provide collateral-free loans to micro and small enterprises. Shishu category covers loans up to ₹50,000 for new businesses in manufacturing, trading, and services sectors. The scheme aims to provide formal finance to the unfunded informal sector and help small businesses grow.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Trading', 'Services'],
    minAmount: 0,
    maxAmount: 50000,
    eligibility: 'Any Indian citizen above 18 years of age can apply. The borrower should have a business plan for new business. For existing businesses, minimum 6 months of operation and GST registration may be required.',
    documents: ['Aadhar Card', 'PAN Card', 'Business Registration Certificate', 'GST Registration', 'Bank Passbook', 'Photograph', 'Business Plan'],
    applyUrl: 'https://mudra.org.in/',
    benefits: 'No collateral required, low interest rates starting from 8.40%, quick loan approval within 15 days, no processing fees for loans up to ₹50,000.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'PM Mudra Yojana - Kishor',
    slug: 'pm-mudra-yojana-kishor',
    shortDescription: 'Loans ₹50,000 to ₹5 lakh for growing small businesses',
    description: 'PM Mudra Yojana Kishor category provides loans ranging from ₹50,000 to ₹5 lakh to small businesses that have been in operation for some time and have a good track record. This category is designed for businesses that need expansion capital and working capital.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 50000,
    maxAmount: 500000,
    eligibility: 'Business should have been in operation for at least 6 months. Annual turnover should be between ₹10 lakh and ₹50 lakh. GST registration is mandatory. Good credit history preferred.',
    documents: ['Aadhar Card', 'PAN Card', 'Business Registration Certificate', 'GST Registration', 'Bank Statement (last 6 months)', 'ITR (last 2 years)', 'Photograph'],
    applyUrl: 'https://mudra.org.in/',
    benefits: 'Competitive interest rates, flexible repayment tenure up to 5 years, quick processing within 7-10 days, no collateral required up to ₹5 lakh.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'PM Mudra Yojana - Tarun',
    slug: 'pm-mudra-yojana-tarun',
    shortDescription: 'Loans ₹5-20 lakh for established small and medium enterprises',
    description: 'PM Mudra Yojana Tarun category provides loans from ₹5 lakh to ₹20 lakh (increased from ₹10 lakh in Budget 2024) to well-established SMEs looking for larger amounts for expansion, modernization, or working capital needs. New Tarun Plus category for repeat borrowers introduced in 2024.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 500000,
    maxAmount: 2000000,
    eligibility: 'Business should have been in operation for at least 1 year. Annual turnover should be above ₹50 lakh. GST registration and audited financial statements mandatory. Strong credit score and track record required. Tarun Plus (₹10L-₹20L) for repeat borrowers who successfully repaid previous Tarun loans.',
    documents: ['Aadhar Card', 'PAN Card', 'Business Registration Certificate', 'GST Registration', 'Audited Financial Statements (last 2 years)', 'Bank Statement (last 1 year)', 'ITR (last 3 years)', 'Photograph', 'Project Report'],
    applyUrl: 'https://www.mudra.org.in/',
    benefits: 'Large loan amounts up to ₹20 lakh (updated 2024), interest rates starting from 8.40%, longer repayment tenure up to 7 years, working capital and term loan options available, no collateral required.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== CREDIT GUARANTEE & FINANCIAL SCHEMES ==========
  {
    name: 'CGTMSE - Credit Guarantee Fund Trust for Micro Enterprises',
    slug: 'cgtmse-credit-guarantee-fund',
    shortDescription: 'Collateral-free loans up to ₹5 crore for MSMEs',
    description: 'CGTMSE (Credit Guarantee Fund Trust for Micro Enterprises) provides credit guarantee to loans extended by Member Lending Institutions (MLIs) to micro and small enterprises. The guarantee covers up to 85% of the loan amount, reducing risk for lenders and enabling easier access to credit for MSMEs.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 100000,
    maxAmount: 50000000,
    eligibility: 'MSMEs in manufacturing and service sectors with annual turnover up to ₹250 crore. New enterprises can get guarantee coverage. GST registration required. No collateral needed for guaranteed loans.',
    documents: ['Aadhar Card', 'PAN Card', 'Business Registration Certificate', 'GST Registration', 'Bank Statement', 'Business Plan', 'Project Report'],
    applyUrl: 'https://cgtmse.org.in/',
    benefits: 'Credit guarantee of up to 85% of loan amount, enabling collateral-free loans up to ₹5 crore, interest rates typically 10-12%, quick processing within 7-10 days.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== ARTISAN & CRAFTSMAN SCHEMES ==========
  {
    name: 'PM Vishwakarma Yojana',
    slug: 'pm-vishwakarma-yojana',
    shortDescription: '₹3 lakh collateral-free loans for traditional artisans',
    description: 'PM Vishwakarma Yojana is a new government scheme launched for traditional artisans and craftsmen. It provides collateral-free loans of up to ₹3 lakh at 5% interest rate, tool kit assistance, and training support to artisans working with tools and equipment.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Handicraft'],
    minAmount: 0,
    maxAmount: 300000,
    eligibility: 'Artisans and craftsmen engaged in traditional work using hand tools or manual tools. Must be 18 years or above. Should have been working in the trade for at least 3 years. Aadhar card mandatory.',
    documents: ['Aadhar Card', 'PAN Card', 'Bank Account', 'Photograph', 'Identity Proof', 'Skill Certificate'],
    applyUrl: 'https://pmvishwakarma.gov.in/',
    benefits: 'Collateral-free loan up to ₹3 lakh at just 5% interest rate, free tool kit worth ₹15,000, training support, marketing assistance, and common facility center access.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== WOMEN & SC/ST SCHEMES ==========
  {
    name: 'Stand Up India Scheme',
    slug: 'stand-up-india-scheme',
    shortDescription: '₹10 lakh-₹1 crore loans for SC/ST and women entrepreneurs',
    description: 'Stand Up India Scheme facilitates bank loans between ₹10 lakh and ₹1 crore to SC/ST and women entrepreneurs for greenfield enterprises. Extended till 2025, the scheme promotes entrepreneurship among scheduled castes, scheduled tribes, and women with composite loan support including both term loan and working capital.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 1000000,
    maxAmount: 10000000,
    eligibility: 'SC/ST and women entrepreneurs aged 18+ starting greenfield enterprises. Loan amount between ₹10 lakh and ₹1 crore. Must have at least 51% ownership. First-generation entrepreneurs preferred. Scheme extended till 2025.',
    documents: ['Aadhar Card', 'PAN Card', 'Caste Certificate (for SC/ST)', 'Bank Account', 'Business Plan', 'Project Report', 'Financial Projections', 'Photograph'],
    applyUrl: 'https://www.standupmitra.in/',
    benefits: 'Composite loan with term loan + working capital, margin money up to 25% of project cost, credit guarantee through NCGTC, handholding support for 2 years, relaxed norms for women/SC/ST entrepreneurs. Over 2.75 lakh beneficiaries supported till date.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Mahila Udyam Nidhi Scheme',
    slug: 'mahila-udyam-nidhi-scheme',
    shortDescription: 'Term loans up to ₹10 lakh for women entrepreneurs',
    description: 'Mahila Udyam Nidhi Scheme by Small Industries Development Bank of India (SIDBI) provides term loans to women entrepreneurs for setting up new ventures or expanding existing ones. This scheme specifically targets women-owned MSMEs in manufacturing and service sectors.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 100000,
    maxAmount: 1000000,
    eligibility: 'Women entrepreneurs (minimum 51% ownership by women). Business registered as proprietorship, partnership, or company. Project cost up to ₹10 lakh. Located in areas with population below 2 lakh.',
    documents: ['Aadhar Card', 'PAN Card', 'Business Registration', 'Project Report', 'Ownership Proof', 'Bank Statement', 'Photograph'],
    applyUrl: 'https://www.sidbi.in/',
    benefits: 'Concessional interest rates for women, loans up to ₹10 lakh, flexible repayment tenure, no collateral for loans below ₹5 lakh, technical and marketing support.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'National SC-ST Hub Scheme',
    slug: 'national-sc-st-hub-scheme',
    shortDescription: 'Procurement preference for SC/ST entrepreneurs',
    description: 'National SC-ST Hub Scheme aims to facilitate procurement of goods and services by Central Public Sector Enterprises (CPSEs) from SC/ST entrepreneurs. The scheme helps SC/ST-owned MSMEs participate in government tenders and secure contracts.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'MSMEs owned by SC/ST entrepreneurs (at least 51% ownership). Valid Udyam Registration. Caste certificate mandatory. Must be capable of supplying goods/services to CPSEs.',
    documents: ['Udyam Certificate', 'Caste Certificate', 'PAN Card', 'Aadhar Card', 'Business Registration', 'Product/Service Catalogue', 'GST Registration'],
    applyUrl: 'https://nssh.gov.in/',
    benefits: '4% procurement target for SC/ST enterprises, tender preference, capacity building support, financial assistance for participating in exhibitions and trade fairs.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== STARTUP & INNOVATION SCHEMES ==========
  {
    name: 'Startup India Seed Fund',
    slug: 'startup-india-seed-fund',
    shortDescription: 'Grants up to ₹50 lakh for early-stage startups',
    description: 'Startup India Seed Fund provides early-stage startups with funding support of up to ₹50 lakh through eligible incubators. ₹20 lakh as grant for proof of concept and ₹50 lakh as investment for prototype development, product trials, and market entry.',
    type: 'central',
    state: null,
    sector: ['Technology', 'Services', 'Manufacturing'],
    minAmount: 0,
    maxAmount: 5000000,
    eligibility: 'Startups incorporated as private limited company or registered partnership firm. Must have DPIIT recognition. Should be in operation for less than 2 years from date of incorporation. Should not have received funding from other government schemes exceeding ₹10 lakh.',
    documents: ['Incorporation Certificate', 'DPIIT Certificate', 'PAN Card', 'Aadhar Card', 'Business Plan', 'Pitch Deck', 'Financial Projections', 'Bank Statement'],
    applyUrl: 'https://www.startupindia.gov.in/',
    benefits: 'Grant funding up to ₹20 lakh for proof of concept, investment up to ₹50 lakh for prototype and market entry, no equity dilution for grant, mentorship support, incubation access.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Atal Innovation Mission (AIM)',
    slug: 'atal-innovation-mission',
    shortDescription: 'Innovation support and funding for tech startups',
    description: 'Atal Innovation Mission promotes innovation and entrepreneurship through Atal Incubation Centers (AICs) and Atal Tinkering Labs. AIM provides grants of up to ₹10 crore to establish incubation centers and supports innovative startups with funding and mentorship.',
    type: 'central',
    state: null,
    sector: ['Technology', 'Innovation', 'Services'],
    minAmount: 0,
    maxAmount: 100000000,
    eligibility: 'Tech startups with innovative solutions. DPIIT recognized startups preferred. Working prototype or MVP required. Focus on deep tech, AI/ML, IoT, biotech, cleantech, and emerging technologies.',
    documents: ['DPIIT Certificate', 'Incorporation Certificate', 'PAN Card', 'Aadhar Card', 'Prototype/MVP Demo', 'Technical Documentation', 'Business Plan'],
    applyUrl: 'https://aim.gov.in/',
    benefits: 'Grants up to ₹10 crore for incubation centers, seed funding for startups, access to mentors and industry experts, networking opportunities, government procurement preference.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'NIDHI - National Initiative for Developing and Harnessing Innovations',
    slug: 'nidhi-scheme',
    shortDescription: 'Nurturing startups and innovation in knowledge-based sectors',
    description: 'NIDHI is an umbrella program by Department of Science and Technology to nurture startups through scouting, supporting, and scaling innovations. It includes multiple sub-schemes like NIDHI-PRAYAS, NIDHI-EIR, and NIDHI-SSS for different stages of startup journey.',
    type: 'central',
    state: null,
    sector: ['Technology', 'Innovation', 'Manufacturing'],
    minAmount: 0,
    maxAmount: 1000000,
    eligibility: 'Student innovators, aspiring entrepreneurs, and early-stage startups with innovative ideas. Preference for knowledge and technology-based innovations. Age limit 18-35 years for individual applicants.',
    documents: ['Aadhar Card', 'PAN Card', 'Educational Certificate', 'Innovation/Project Description', 'Prototype/Proof of Concept', 'Photograph'],
    applyUrl: 'https://nidhi.dsir.gov.in/',
    benefits: 'Grant support up to ₹10 lakh for prototype development, seed funding, entrepreneurship training, mentorship, incubation support, networking with investors.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== TECHNOLOGY & MODERNIZATION SCHEMES ==========
  {
    name: 'CLCSS - Credit Linked Capital Subsidy Scheme',
    slug: 'clcss-credit-linked-subsidy',
    shortDescription: '15% capital subsidy on technology equipment purchases',
    description: 'CLCSS provides 15% capital subsidy on purchases of eligible plant and machinery for MSMEs in manufacturing sectors. The subsidy is directly credited to the borrower\'s account with the lending institution. This helps MSMEs modernize with advanced technology at reduced cost.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Technology'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'MSMEs in manufacturing sector. Must have a business plan. Should purchase eligible plant/machinery. Minimum 10% promoter contribution required. GST registration mandatory.',
    documents: ['Aadhar Card', 'PAN Card', 'Business Registration Certificate', 'GST Registration', 'Business Plan', 'Quotation from Supplier', 'Bank Account', 'Identity Proof', 'Photograph'],
    applyUrl: 'https://www.dcmsme.gov.in/',
    benefits: '15% subsidy on technology equipment, maximum subsidy ₹15 lakh, reduces capital cost, enables modernization with latest technology, quick processing.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Technology Upgradation Fund Scheme (TUFS)',
    slug: 'technology-upgradation-fund-scheme',
    shortDescription: 'Interest subsidy for textile industry modernization',
    description: 'TUFS provides interest subsidy and capital investment support to textile and jute industries for technology upgradation. The scheme covers spinning, weaving, processing, and garmenting segments with focus on modernization and energy efficiency.',
    type: 'central',
    state: null,
    sector: ['Textile', 'Manufacturing'],
    minAmount: 1000000,
    maxAmount: 200000000,
    eligibility: 'Textile and jute manufacturing units. MSMEs and large enterprises eligible. Project should involve technology upgradation. Minimum investment ₹10 lakh required.',
    documents: ['Udyam Certificate', 'Project Report', 'Financial Statements', 'GST Registration', 'Land Documents', 'Environmental Clearance', 'Bank Account'],
    applyUrl: 'https://www.texmin.nic.in/',
    benefits: '5% interest reimbursement for 7 years, additional 2% for water jet and air jet looms, capital subsidy component available, promotes energy-efficient machinery.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'ZED - Zero Defect Zero Effect Scheme',
    slug: 'zed-certification-scheme',
    shortDescription: 'Quality certification and subsidy for MSMEs',
    description: 'ZED Certification Scheme promotes adoption of Zero Defect Zero Effect manufacturing practices among MSMEs. The scheme provides financial support for certification costs and helps MSMEs improve quality, productivity, and environmental sustainability.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'All MSMEs with Udyam Registration. Both manufacturing and service sectors eligible. No minimum turnover requirement. First-time certification applicants preferred.',
    documents: ['Udyam Certificate', 'Aadhar Card', 'PAN Card', 'GST Registration', 'Bank Account', 'Company Profile'],
    applyUrl: 'https://zed.msme.gov.in/',
    benefits: '80% subsidy on certification costs for micro enterprises, 60% for small, free handholding support, quality improvement training, enhanced competitiveness, access to government procurement.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== EMPLOYMENT & SKILL SCHEMES ==========
  {
    name: 'PMEGP - Prime Minister\'s Employment Generation Programme',
    slug: 'pmegp',
    shortDescription: '35% subsidy for setting up micro enterprises',
    description: 'PMEGP provides subsidy of 35% of project cost (general category) or 25% (special category) for setting up new micro enterprises. The scheme covers manufacturing, services, and business sectors and is implemented through Khadi and Village Industries Commission (KVIC) and District Industries Centers (DIC).',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading', 'Agriculture'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'New entrepreneurs starting manufacturing/service/business enterprise. Minimum 8th pass for general category, no minimum education for special category. Age above 18 years. Project cost: ₹10 lakh-₹25 lakh for manufacturing, ₹5 lakh-₹10 lakh for services. Must have own contribution of at least 10%.',
    documents: ['Aadhar Card', 'PAN Card', 'Educational Qualification Certificate', 'Caste Certificate (if applicable)', 'Project Report', 'Quotations', 'Bank Account', 'Photograph'],
    applyUrl: 'https://www.kvic.org.in/pmegp',
    benefits: '15-35% subsidy on project cost (up to ₹17.5 lakh), loan support up to ₹40 lakh for manufacturing and ₹20 lakh for services, no collateral required for loans below ₹10 lakh, technical assistance, marketing support.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'PM SVANidhi - Micro Credit Scheme for Street Vendors',
    slug: 'pm-svanidhi',
    shortDescription: '₹10,000 working capital loans for street vendors',
    description: 'PM SVANidhi scheme provides working capital assistance up to ₹10,000 to street vendors to help them restart their business activities. The scheme supports small vendors with interest subsidy and cash-back incentives for digital transactions.',
    type: 'central',
    state: null,
    sector: ['Services', 'Trading'],
    minAmount: 0,
    maxAmount: 10000,
    eligibility: 'Street vendors with Certificate of Vending or Letter of Recommendation. Vendors doing business as of March 24, 2020. No upper age limit. No requirement of income tax return or GST registration.',
    documents: ['Aadhar Card', 'Vendor ID/Certificate of Vending', 'Mobile Number linked to Aadhar', 'Photograph', 'Bank Account'],
    applyUrl: 'https://pmsvanidhi.mohua.gov.in/',
    benefits: '₹10,000 working capital loan with 7% interest subsidy on regular repayment, cashback up to ₹100/month for digital transactions, eligible for second loan of ₹20,000 after full repayment, third loan of ₹50,000 available.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== REGISTRATION & COMPLIANCE SCHEMES ==========
  {
    name: 'Udyam Registration Certificate',
    slug: 'udyam-registration',
    shortDescription: 'Free MSME registration for all government benefits',
    description: 'Udyam Registration is the official government registration system for MSMEs. It replaces the older MSME registration process and provides a unique identification number and certificate to micro, small, and medium enterprises. Registration is free, online, and mandatory for accessing government schemes.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'Any business entity engaged in manufacturing or service sector. Can be registered as proprietorship, partnership, company, LLP, or cooperative society. Aadhar number and GSTIN mandatory for registration.',
    documents: ['Aadhar Card', 'PAN Card', 'GST Number (if applicable)', 'Bank Account'],
    applyUrl: 'https://udyamregistration.gov.in/',
    benefits: 'Free registration, lifetime validity, automatic classification as MSME, priority access to all government schemes, easier bank loans, government tender preference, no renewal required.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== EXPORT PROMOTION SCHEMES ==========
  {
    name: 'Interest Equalization Scheme for MSMEs',
    slug: 'interest-equalization-scheme-msme',
    shortDescription: '3-5% interest subsidy on export credit',
    description: 'Interest Equalization Scheme provides interest subsidy at the rate of 3% for MSMEs and 5% for select sectors on pre-shipment and post-shipment rupee export credit. The scheme aims to enhance export competitiveness of MSMEs.',
    type: 'central',
    state: null,
    sector: ['Export', 'Manufacturing', 'Services'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'MSMEs engaged in exports with Udyam Registration. Valid IEC (Import Export Code) required. Pre-shipment and post-shipment export credit from banks eligible. 410 tariff lines covered under the scheme.',
    documents: ['Udyam Certificate', 'IEC Code', 'GST Registration', 'Export Orders', 'Shipping Documents', 'Bank Certificate'],
    applyUrl: 'https://www.dgft.gov.in/',
    benefits: '3% interest equalization for MSMEs, 5% for specified sectors, applies to both pre and post-shipment credit, reduces export financing cost, automatic benefits through banks.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Market Access Initiative (MAI) Scheme',
    slug: 'market-access-initiative-scheme',
    shortDescription: 'Export promotion and market development support',
    description: 'MAI Scheme provides financial assistance for export promotion activities like participation in international trade fairs, buyer-seller meets, market studies, and export publicity. The scheme helps MSMEs access international markets and increase exports.',
    type: 'central',
    state: null,
    sector: ['Export', 'Manufacturing', 'Services'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'Export promotion councils, commodity boards, industry associations, and individual exporters. MSMEs get preference. Valid IEC code required. Previous export track record preferred.',
    documents: ['IEC Code', 'Udyam Certificate', 'Export Performance Certificate', 'Association Membership', 'Event Registration'],
    applyUrl: 'https://www.commerce.gov.in/',
    benefits: 'Financial assistance for trade fair participation, market study funding, buyer-seller meet support, export publicity assistance, space rental subsidy, travel support.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'EPCG Scheme - Export Promotion Capital Goods',
    slug: 'epcg-scheme',
    shortDescription: 'Zero duty import of capital goods for exporters',
    description: 'EPCG Scheme allows import of capital goods for pre-production, production, and post-production at zero customs duty. The scheme is available to manufacturer exporters and merchant exporters tied to supporting manufacturers. Export obligation of 6 times the duty saved over 6 years.',
    type: 'central',
    state: null,
    sector: ['Export', 'Manufacturing'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'Manufacturer exporters or merchant exporters with supporting manufacturers. Valid IEC code required. Minimum export track record preferred. Should fulfill export obligation.',
    documents: ['IEC Code', 'Udyam Certificate', 'Export Performance Certificate', 'Proforma Invoice of Capital Goods', 'Bank Guarantee'],
    applyUrl: 'https://www.dgft.gov.in/',
    benefits: 'Zero customs duty on capital goods import, improved productivity with modern machinery, reduced capital cost, 6 times duty saved as export obligation over 6 years.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== SECTOR-SPECIFIC SCHEMES ==========
  {
    name: 'Modified SFURTI Scheme - Khadi Clusters',
    slug: 'sfurti-khadi-clusters',
    shortDescription: 'Cluster development for traditional industries',
    description: 'Scheme of Fund for Regeneration of Traditional Industries (SFURTI) aims to make traditional industries more productive and competitive through cluster-based development approach. Covers khadi, village industries, coir, and other traditional sectors.',
    type: 'central',
    state: null,
    sector: ['Handicraft', 'Manufacturing', 'Agriculture'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'Traditional artisans and workers in khadi, handloom, coir, bamboo, pottery sectors. Cluster should have minimum 500 artisans for soft intervention, 200 for hard intervention.',
    documents: ['Aadhar Card', 'Artisan ID Card', 'Cluster Registration', 'Project Proposal', 'Bank Account'],
    applyUrl: 'https://sfurti.msme.gov.in/',
    benefits: 'Common facility centers, raw material banks, design and technology support, training programs, marketing assistance, brand development, up to ₹8 crore per cluster.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Coir Udyami Yojana',
    slug: 'coir-udyami-yojana',
    shortDescription: 'Financial assistance for coir manufacturing units',
    description: 'Coir Udyami Yojana provides financial assistance for setting up coir manufacturing units, modernization of existing units, and technology upgradation. The scheme is implemented through Coir Board under Ministry of MSME.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Handicraft'],
    minAmount: 0,
    maxAmount: 1000000,
    eligibility: 'Individuals, Self Help Groups, Co-operative Societies engaged in coir production. Preference for SC/ST/Women/BPL families. Unit should be in coir-producing states.',
    documents: ['Aadhar Card', 'PAN Card', 'Caste Certificate (if applicable)', 'Project Report', 'Land Documents', 'Bank Account'],
    applyUrl: 'https://coirboard.gov.in/',
    benefits: 'Subsidy up to 40% of project cost (maximum ₹4 lakh), margin money assistance, working capital support, skill training, marketing support.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'PMFME - PM Formalization of Micro Food Processing Enterprises',
    slug: 'pmfme-scheme',
    shortDescription: 'Support for micro food processing units',
    description: 'PMFME Scheme provides financial, technical, and business support to micro food processing enterprises. The scheme aims to enhance competitiveness of existing individual micro-enterprises, support FPOs, and encourage formalization of the sector.',
    type: 'central',
    state: null,
    sector: ['Food Processing', 'Manufacturing', 'Agriculture'],
    minAmount: 0,
    maxAmount: 1000000,
    eligibility: 'Individual entrepreneurs, Self Help Groups, FPOs, Cooperatives in food processing. Annual turnover below ₹2 crore. Investment in plant and machinery below ₹1 crore.',
    documents: ['Aadhar Card', 'Udyam Registration', 'FSSAI License', 'Project Report', 'Bank Account', 'GST Registration'],
    applyUrl: 'https://pmfme.mofpi.gov.in/',
    benefits: '35% credit-linked subsidy (maximum ₹10 lakh per unit), seed capital to FPOs/SHGs/Cooperatives, training and handholding support, marketing and branding assistance.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Production Linked Incentive (PLI) - Textiles',
    slug: 'pli-textiles',
    shortDescription: 'Incentive scheme for textile manufacturing',
    description: 'PLI Scheme for Textiles provides incentive of up to 15% on incremental turnover of products manufactured in India. Focus on MMF (Man-Made Fiber) apparel, MMF fabrics, and technical textiles to boost domestic manufacturing and exports.',
    type: 'central',
    state: null,
    sector: ['Textile', 'Manufacturing', 'Export'],
    minAmount: 100000000,
    maxAmount: 0,
    eligibility: 'Manufacturing companies in MMF segment, technical textiles. Minimum investment: ₹300 crore for large entities, ₹100 crore for small entities. Should achieve minimum turnover targets.',
    documents: ['Company Registration', 'PAN Card', 'GST Registration', 'Investment Proof', 'Production Data', 'Financial Statements'],
    applyUrl: 'https://www.texmin.nic.in/',
    benefits: '11-15% incentive on incremental turnover for 5 years, promotes investment, enhances export competitiveness, creates employment opportunities.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== CREDIT & FINANCE SCHEMES ==========
  {
    name: 'SIDBI Make in India Loan for Enterprises',
    slug: 'sidbi-smile-loan',
    shortDescription: 'SMILE loans up to ₹10 crore for MSMEs',
    description: 'SIDBI Make in India Loan for Enterprises (SMILE) provides quick and hassle-free loans to MSMEs for business expansion, modernization, and working capital. The scheme focuses on supporting Make in India initiative.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services'],
    minAmount: 1000000,
    maxAmount: 100000000,
    eligibility: 'Existing MSMEs with track record of 3+ years. Annual turnover minimum ₹5 crore. Good credit rating required. Manufacturing and service sector units.',
    documents: ['Udyam Certificate', 'Financial Statements (last 3 years)', 'ITR', 'Bank Statements', 'GST Returns', 'Project Report'],
    applyUrl: 'https://www.sidbi.in/',
    benefits: 'Loans up to ₹10 crore, competitive interest rates, quick approval, minimal documentation, longer repayment tenure up to 10 years.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Emergency Credit Line Guarantee Scheme (ECLGS)',
    slug: 'eclgs-scheme',
    shortDescription: 'Additional collateral-free credit for COVID-19 recovery',
    description: 'ECLGS provides 100% guarantee coverage to banks and NBFCs for additional working capital term loans extended to eligible MSMEs and business enterprises. The scheme helps businesses recover from COVID-19 impact.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'MSMEs with outstanding credit up to ₹500 crore as on Feb 29, 2020. Account should be regular or SMA-0. No defaults or NPA as on Feb 29, 2020. Business enterprises in hospitality, travel, leisure sectors also eligible.',
    documents: ['Udyam Certificate', 'Existing Loan Documents', 'Bank Statements', 'GST Returns', 'Financial Statements'],
    applyUrl: 'https://www.ncgtc.in/',
    benefits: '40% additional credit (up to ₹200 crore), 100% guarantee by NCGTC, moratorium of 1 year, tenure of 5-6 years, no collateral, no guarantee fees for borrower.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== GREEN & SUSTAINABLE SCHEMES ==========
  {
    name: 'National Solar Mission - Rooftop Solar Subsidy',
    slug: 'rooftop-solar-subsidy-msme',
    shortDescription: '40% subsidy for rooftop solar installations',
    description: 'Grid-Connected Rooftop Solar Programme provides subsidy for installation of rooftop solar PV systems. MSMEs can get subsidy support for reducing electricity costs and contributing to clean energy transition.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Green Energy'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'MSMEs, residential, institutional, and commercial establishments. System capacity should be suitable for rooftop. Grid connectivity required.',
    documents: ['Electricity Bill', 'Property Ownership Proof', 'Aadhar Card', 'PAN Card', 'Bank Account', 'Technical Proposal'],
    applyUrl: 'https://solarrooftop.gov.in/',
    benefits: '40% subsidy for systems up to 3 kW, 20% for systems 3-10 kW, reduces electricity bills, 25-year operational life, net metering benefits, clean energy contribution.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== MARKETING & PROCUREMENT SCHEMES ==========
  {
    name: 'GeM - Government e-Marketplace',
    slug: 'gem-registration',
    shortDescription: 'Direct access to government procurement marketplace',
    description: 'GeM is an online platform for government procurement of goods and services. MSMEs can register on GeM to sell directly to government departments and PSUs. Special provisions for startups and MSEs including exemption from EMD and performance security.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'Any business entity - proprietorship, partnership, company, LLP. Valid PAN and GST registration required. Product/service should match GeM categories. Quality certifications preferred.',
    documents: ['PAN Card', 'GST Registration', 'Udyam Certificate', 'Bank Account with Cancelled Cheque', 'Product Catalogue', 'Quality Certificates'],
    applyUrl: 'https://gem.gov.in/',
    benefits: 'Direct access to government buyers, no tender fees, no EMD for startups/MSEs, advance payment option, automatic payment within 10 days, 25% procurement target for MSEs.',
    isActive: true,
    isFeatured: true,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== ADDITIONAL CENTRAL SCHEMES ==========
  {
    name: 'ASPIRE - Scheme for Promotion of Innovation and Rural Entrepreneurship',
    slug: 'aspire-scheme',
    shortDescription: 'Support for innovation and rural entrepreneurship',
    description: 'ASPIRE scheme promotes innovation and entrepreneurship in agro-industry through establishment of Livelihood Business Incubators (LBIs) and Technology Business Incubators (TBIs) in rural areas. Provides incubation support, funding, and mentorship.',
    type: 'central',
    state: null,
    sector: ['Agriculture', 'Rural', 'Innovation'],
    minAmount: 0,
    maxAmount: 10000000,
    eligibility: 'Startups and enterprises in agro-based industries. Rural entrepreneurs, farmers, artisans. Focus on innovative business models in agriculture, food processing, and allied sectors.',
    documents: ['Aadhar Card', 'Business Plan', 'Project Report', 'Bank Account', 'Rural Address Proof'],
    applyUrl: 'https://www.dcmsme.gov.in/',
    benefits: 'Funding support up to ₹1 crore for incubators, soft loan/grant to incubatees, mentorship and handholding, access to testing facilities, marketing support.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'MSE-CDP - MSE Cluster Development Programme',
    slug: 'mse-cluster-development',
    shortDescription: 'Cluster-based development for MSMEs',
    description: 'MSE-CDP supports MSME clusters through capacity building, skill development, marketing support, and technology upgradation. Diagnostic study and soft interventions provided to improve cluster competitiveness.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Handicraft'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'MSME clusters with minimum 25-50 units in a geographical area. Clusters in both traditional and modern sectors. SPV/Cluster Association should be formed.',
    documents: ['Cluster Registration', 'Member List', 'Project Proposal', 'SPV Documents'],
    applyUrl: 'https://www.dcmsme.gov.in/',
    benefits: 'Diagnostic study support, capacity building programs, technology interventions, marketing assistance, networking with buyers, up to ₹2.5 crore per cluster.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Credit Guarantee Scheme for Subordinate Debt (CGSSD)',
    slug: 'cgssd-scheme',
    shortDescription: 'Subordinate debt for stressed MSMEs',
    description: 'CGSSD provides guarantee cover to banks for extending subordinate debt to promoters of stressed MSMEs. The scheme helps promoters of viable MSMEs facing stress to meet their equity/quasi-equity requirements.',
    type: 'central',
    state: null,
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'Promoters of MSMEs which are NPA or SMA-2. Promoter should not be willful defaulter. Credit facility should not exceed ₹25 crore. Unit should be viable.',
    documents: ['Udyam Certificate', 'Existing Loan Details', 'Financial Statements', 'Viability Report', 'Promoter Documents'],
    applyUrl: 'https://www.ncgtc.in/',
    benefits: '90% guarantee by NCGTC, maximum ₹2 crore per borrower, helps in debt restructuring, moratorium of 7 years, promotes MSMEs revival.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
]

export const STATE_SCHEMES = [
  // ========== MAHARASHTRA ==========
  {
    name: 'Maharashtra State Financial Corporation (MSFC) Loan Scheme',
    slug: 'maharashtra-msfc-loan',
    shortDescription: 'Subsidized loans for MSMEs in Maharashtra',
    description: 'Maharashtra State Financial Corporation (MSFC) provides subsidized loans and financial assistance to MSMEs in the state. The scheme offers term loans, working capital loans, and equipment loans at subsidized interest rates to promote industrial development.',
    type: 'state',
    state: 'maharashtra',
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 50000,
    maxAmount: 10000000,
    eligibility: 'MSMEs registered in Maharashtra with valid Udyam certificate. Must have been in operation for at least 1 year. Annual turnover up to ₹50 lakh. Good credit score preferred.',
    documents: ['Udyam Registration Certificate', 'Aadhar Card', 'PAN Card', 'Business Registration', 'Bank Statement', 'Maharashtra Address Proof', 'Photograph'],
    applyUrl: 'https://www.maharashtra.gov.in/',
    benefits: 'Subsidized interest rates, flexible repayment tenure up to 7 years, quick processing within 7-10 days, no processing fees, up to ₹1 crore loan amount available.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Maharashtra Industrial Policy 2024 - Investment Subsidy',
    slug: 'maharashtra-investment-subsidy',
    shortDescription: 'Capital investment subsidy for new manufacturing units',
    description: 'Maharashtra Industrial Policy 2024 provides capital investment subsidy ranging from 25-50% for new manufacturing units and expansion projects. Focus on promoting investment in backward regions and emerging sectors.',
    type: 'state',
    state: 'maharashtra',
    sector: ['Manufacturing'],
    minAmount: 10000000,
    maxAmount: 0,
    eligibility: 'New manufacturing units or substantial expansion. Minimum fixed capital investment ₹1 crore. Must create employment as per policy norms. Located in eligible areas - D+, C, D categories get higher subsidy.',
    documents: ['Project Report', 'Land Documents', 'Environmental Clearance', 'Udyam Certificate', 'Investment Proof', 'Employment Details'],
    applyUrl: 'https://www.maharashtraindustry.com/',
    benefits: '25-50% capital investment subsidy based on location, interest subsidy, stamp duty exemption, electricity duty exemption, employment generation subsidy.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Atal Saur Krushi Pump Yojana - Maharashtra',
    slug: 'maharashtra-solar-pump',
    shortDescription: 'Subsidized solar pumps for agriculture MSMEs',
    description: 'Atal Saur Krushi Pump Yojana provides solar-powered agricultural pump sets with 95% subsidy for farmers and agri-MSMEs. Helps reduce electricity costs and promote sustainable agriculture.',
    type: 'state',
    state: 'maharashtra',
    sector: ['Agriculture', 'Green Energy'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'Farmers and agricultural enterprises in Maharashtra. Electricity connection in applicant name. Suitable land for solar panel installation.',
    documents: ['7/12 Extract', 'Electricity Bill', 'Aadhar Card', 'Bank Account', 'Consent Letter'],
    applyUrl: 'https://www.mahadiscom.in/',
    benefits: '95% subsidy (90% government + 5% DISCOM), 3 HP to 10 HP capacity, reduces electricity bills, 25-year life, free maintenance for 5 years.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== GUJARAT ==========
  {
    name: 'Gujarat MSME Loan Scheme',
    slug: 'gujarat-msme-loan',
    shortDescription: 'Financial assistance for MSMEs in Gujarat',
    description: 'Gujarat government provides various loan schemes and financial assistance programs for MSMEs through Gujarat Financial Corporation and other state agencies. These schemes offer term loans, working capital, and equipment loans at competitive rates.',
    type: 'state',
    state: 'gujarat',
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 50000,
    maxAmount: 15000000,
    eligibility: 'MSMEs registered in Gujarat with Udyam certificate. Must have been in operation for at least 2 years. Annual turnover up to ₹100 lakh. Good credit history required.',
    documents: ['Udyam Registration Certificate', 'Aadhar Card', 'PAN Card', 'Business Registration', 'Bank Statement', 'Gujarat Domicile Certificate', 'Photograph'],
    applyUrl: 'https://www.gujfin.gov.in/',
    benefits: 'Competitive interest rates, longer repayment tenure, no processing fees, up to ₹1.5 crore loan amount available, quick processing.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'iNDEXTb - Gujarat Biotechnology Start-up Scheme',
    slug: 'gujarat-biotechnology-startup',
    shortDescription: 'Support for biotech startups and MSMEs',
    description: 'iNDEXTb scheme supports biotechnology startups and MSMEs in Gujarat with incubation facilities, funding support, mentorship, and market access. Focus on healthcare, agriculture, and industrial biotech.',
    type: 'state',
    state: 'gujarat',
    sector: ['Technology', 'Innovation', 'Healthcare'],
    minAmount: 0,
    maxAmount: 5000000,
    eligibility: 'Biotech startups and MSMEs in Gujarat. DPIIT recognition preferred. Focus on innovative solutions in healthcare, agriculture, industrial biotech.',
    documents: ['DPIIT Certificate', 'Incorporation Certificate', 'Project Proposal', 'Technical Details', 'Founder Details'],
    applyUrl: 'https://www.indextb.com/',
    benefits: 'Incubation space at subsidized rates, seed funding up to ₹50 lakh, mentorship from industry experts, access to testing facilities, networking opportunities.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== TAMIL NADU ==========
  {
    name: 'Tamil Nadu MSME Loan Scheme',
    slug: 'tamil-nadu-msme-loan',
    shortDescription: 'Low-interest loans for MSMEs in Tamil Nadu',
    description: 'Tamil Nadu Industrial Investment Corporation (TIIC) provides financial assistance to MSMEs in the state. The scheme offers term loans, working capital loans, and equipment loans at subsidized rates to promote industrial growth.',
    type: 'state',
    state: 'tamil-nadu',
    sector: ['Manufacturing', 'Services'],
    minAmount: 50000,
    maxAmount: 10000000,
    eligibility: 'MSMEs registered in Tamil Nadu with valid Udyam certificate. Must have been in operation for at least 3 years. Annual turnover up to ₹50 lakh. Tamil Nadu domicile required.',
    documents: ['Udyam Registration Certificate', 'Aadhar Card', 'PAN Card', 'Business Registration', 'Bank Statement', 'Tamil Nadu Domicile Certificate', 'Photograph'],
    applyUrl: 'https://www.tnidc.in/',
    benefits: 'Subsidized interest rates, processing time 7-10 days, no hidden charges, up to ₹1 crore loan amount, technical assistance available.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Tamil Nadu Startup and Innovation Policy',
    slug: 'tamil-nadu-startup-innovation',
    shortDescription: 'Comprehensive support for startups and innovators',
    description: 'Tamil Nadu Startup Policy provides comprehensive ecosystem support including funding, mentorship, incubation, and market access. Aims to establish Tamil Nadu as leading startup destination.',
    type: 'state',
    state: 'tamil-nadu',
    sector: ['Technology', 'Innovation', 'Services'],
    minAmount: 0,
    maxAmount: 10000000,
    eligibility: 'Startups incorporated in Tamil Nadu. DPIIT recognition preferred. Focus on innovative and scalable business models. Age of company less than 7 years.',
    documents: ['Incorporation Certificate', 'DPIIT Recognition', 'Business Plan', 'Founder Details', 'Tamil Nadu Registration Proof'],
    applyUrl: 'https://startuphttps://www.startuptn.in/',
    benefits: 'Seed funding up to ₹10 lakh, incubation support, mentorship, co-working space subsidy, reimbursement of patent filing costs, marketing support.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== KARNATAKA ==========
  {
    name: 'Karnataka MSME Loan Scheme',
    slug: 'karnataka-msme-loan',
    shortDescription: 'Financial support for MSMEs in Karnataka',
    description: 'Karnataka State Financial Corporation (KSFC) provides term loans, working capital loans, and equipment loans to MSMEs in the state. The scheme offers financial assistance at subsidized rates to promote MSME development.',
    type: 'state',
    state: 'karnataka',
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 50000,
    maxAmount: 12000000,
    eligibility: 'MSMEs registered in Karnataka with valid Udyam certificate. Must have been in operation for at least 2 years. Annual turnover up to ₹100 lakh. Good credit score required.',
    documents: ['Udyam Registration Certificate', 'Aadhar Card', 'PAN Card', 'Business Registration', 'Bank Statement', 'Karnataka Domicile Certificate', 'Photograph'],
    applyUrl: 'https://www.ksfc.kar.nic.in/',
    benefits: 'Competitive interest rates, quick processing, no processing fees, up to ₹1.2 crore loan amount available, flexible repayment options.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Elevate Karnataka - Startup Support',
    slug: 'elevate-karnataka',
    shortDescription: 'Funding and mentorship for Karnataka startups',
    description: 'Elevate is Karnataka government flagship program to identify and nurture innovative startups. Provides funding, mentorship, and market access to help startups scale their businesses.',
    type: 'state',
    state: 'karnataka',
    sector: ['Technology', 'Innovation', 'Services'],
    minAmount: 0,
    maxAmount: 5000000,
    eligibility: 'Startups registered in Karnataka. Should have innovative and scalable business model. DPIIT recognition preferred. Pre-revenue or early revenue stage.',
    documents: ['Incorporation Certificate', 'DPIIT Certificate', 'Pitch Deck', 'Business Model', 'Founder Details'],
    applyUrl: 'https://www.elevate.karnataka.gov.in/',
    benefits: 'Grant funding up to ₹50 lakh, mentorship from industry leaders, access to incubation centers, investor connect, government procurement opportunities.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== RAJASTHAN ==========
  {
    name: 'Rajasthan MSME Financial Assistance',
    slug: 'rajasthan-msme-loan',
    shortDescription: 'Government-backed loans for Rajasthan MSMEs',
    description: 'Rajasthan State Financial Corporation (RSFC) provides financial assistance to MSMEs in the state. The scheme offers term loans, working capital loans, and equipment loans at government-subsidized rates.',
    type: 'state',
    state: 'rajasthan',
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 50000,
    maxAmount: 10000000,
    eligibility: 'MSMEs registered in Rajasthan with valid Udyam certificate. Must have been in operation for at least 2 years. Annual turnover up to ₹50 lakh. Rajasthan domicile required.',
    documents: ['Udyam Registration Certificate', 'Aadhar Card', 'PAN Card', 'Business Registration', 'Bank Statement', 'Rajasthan Domicile Certificate', 'Photograph'],
    applyUrl: 'https://industries.rajasthan.gov.in/',
    benefits: 'Government-subsidized interest rates, longer repayment tenure, no processing fees, up to ₹1 crore loan amount, technical guidance available.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Rajasthan Investment Promotion Scheme 2024',
    slug: 'rajasthan-investment-promotion',
    shortDescription: 'Investment subsidy and incentives for industries',
    description: 'RIPS 2024 provides capital investment subsidy, interest subsidy, and various fiscal incentives to promote investment in Rajasthan. Special focus on backward districts and thrust sectors.',
    type: 'state',
    state: 'rajasthan',
    sector: ['Manufacturing', 'Services'],
    minAmount: 5000000,
    maxAmount: 0,
    eligibility: 'New manufacturing units or expansion projects in Rajasthan. Minimum investment ₹50 lakh. Must create employment. Higher incentives for backward districts.',
    documents: ['Project Report', 'Land Documents', 'Investment Proof', 'Udyam Certificate', 'Environmental Clearances'],
    applyUrl: 'https://invest.rajasthan.gov.in/',
    benefits: '30-50% capital investment subsidy, interest subsidy, stamp duty exemption, electricity duty exemption, land subsidy in backward areas.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== UTTAR PRADESH ==========
  {
    name: 'Uttar Pradesh MSME Scheme',
    slug: 'uttar-pradesh-msme-loan',
    shortDescription: 'Financial assistance for MSMEs in Uttar Pradesh',
    description: 'Uttar Pradesh government provides various MSME loan schemes through Uttar Pradesh Financial Corporation (UPFC) and other state agencies. These schemes offer term loans, working capital, and equipment loans at competitive rates.',
    type: 'state',
    state: 'uttar-pradesh',
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 50000,
    maxAmount: 15000000,
    eligibility: 'MSMEs registered in Uttar Pradesh with valid Udyam certificate. Must have been in operation for at least 2 years. Annual turnover up to ₹100 lakh. UP domicile certificate required.',
    documents: ['Udyam Registration Certificate', 'Aadhar Card', 'PAN Card', 'Business Registration', 'Bank Statement', 'Uttar Pradesh Domicile Certificate', 'Photograph'],
    applyUrl: 'https://diupmsme.upsdc.gov.in/',
    benefits: 'Competitive interest rates, quick processing time 7-10 days, up to ₹1.5 crore loan amount available, no processing charges, technical assistance.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'UP Startup Policy - Seed Funding',
    slug: 'up-startup-seed-funding',
    shortDescription: 'Seed funding for startups in Uttar Pradesh',
    description: 'UP Startup Policy provides seed funding support to early-stage startups through Startup Seed Fund. Aims to create vibrant startup ecosystem in Uttar Pradesh.',
    type: 'state',
    state: 'uttar-pradesh',
    sector: ['Technology', 'Innovation', 'Services'],
    minAmount: 0,
    maxAmount: 2500000,
    eligibility: 'Startups incorporated in UP. DPIIT recognition required. Age less than 2 years from incorporation. Innovative and scalable business model.',
    documents: ['Incorporation Certificate', 'DPIIT Certificate', 'Business Plan', 'Pitch Deck', 'Founder Details', 'UP Registration Proof'],
    applyUrl: 'https://startup.up.gov.in/',
    benefits: 'Seed funding up to ₹25 lakh, incubation support, mentorship, co-working space subsidy, stamp duty exemption, quality certification reimbursement.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== WEST BENGAL ==========
  {
    name: 'West Bengal MSME Loan Scheme',
    slug: 'west-bengal-msme-loan',
    shortDescription: 'Government loans for MSMEs in West Bengal',
    description: 'West Bengal government provides MSME loan schemes through West Bengal Financial Corporation (WBFC) and other state agencies. These schemes offer term loans, working capital, and equipment loans at subsidized rates to promote MSME growth.',
    type: 'state',
    state: 'west-bengal',
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 50000,
    maxAmount: 10000000,
    eligibility: 'MSMEs registered in West Bengal with valid Udyam certificate. Must have been in operation for at least 2 years. Annual turnover up to ₹50 lakh. West Bengal domicile certificate needed.',
    documents: ['Udyam Registration Certificate', 'Aadhar Card', 'PAN Card', 'Business Registration', 'Bank Statement', 'West Bengal Domicile Certificate', 'Photograph'],
    applyUrl: 'https://wb.gov.in/',
    benefits: 'Subsidized interest rates, processing time 7-10 days, no processing fees, up to ₹1 crore loan amount, technical and marketing support available.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'Karma Sathi Prakalpa - West Bengal',
    slug: 'karma-sathi-prakalpa',
    shortDescription: 'Skill training and self-employment support',
    description: 'Karma Sathi Prakalpa provides skill training and financial assistance for self-employment to unemployed youth in West Bengal. Focus on creating sustainable livelihoods through entrepreneurship.',
    type: 'state',
    state: 'west-bengal',
    sector: ['Services', 'Trading', 'Manufacturing'],
    minAmount: 0,
    maxAmount: 200000,
    eligibility: 'Unemployed youth in West Bengal aged 18-45 years. Preference for economically weaker sections, SC/ST, minorities, women. Should complete skill training program.',
    documents: ['Aadhar Card', 'Age Proof', 'Income Certificate', 'Caste Certificate (if applicable)', 'Training Certificate', 'Business Proposal'],
    applyUrl: 'https://wbmsme.gov.in/',
    benefits: 'Free skill training, loan up to ₹2 lakh at subsidized rates, marketing support, backward and forward linkages, handholding for 2 years.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== TELANGANA ==========
  {
    name: 'Telangana State Industrial Project Approval',
    slug: 'telangana-ts-ipass',
    shortDescription: 'Single window clearance for industries',
    description: 'TS-iPASS provides single window clearance for industrial projects in Telangana. Online portal for all approvals, licenses, and registrations required to set up industry.',
    type: 'state',
    state: 'telangana',
    sector: ['Manufacturing', 'Services'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'New industrial projects or expansion in Telangana. All sectors covered. Micro, small, medium, and large industries eligible.',
    documents: ['Project Report', 'Land Documents', 'Incorporation Certificate', 'PAN Card', 'Udyam Certificate'],
    applyUrl: 'https://ipass.telangana.gov.in/',
    benefits: 'Single window clearance within 15 days, online application and tracking, 58 clearances covered, deemed approval if delayed, investment subsidy available.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
  {
    name: 'T-Hub Startup Support - Telangana',
    slug: 'telangana-thub-startup',
    shortDescription: 'Innovation hub and startup incubation',
    description: 'T-Hub is India\'s leading innovation hub and startup incubator in Telangana. Provides mentorship, funding connect, infrastructure, and market access to startups and MSMEs.',
    type: 'state',
    state: 'telangana',
    sector: ['Technology', 'Innovation', 'Services'],
    minAmount: 0,
    maxAmount: 0,
    eligibility: 'Startups and MSMEs with innovative and scalable business models. Focus on technology-enabled solutions. DPIIT recognition preferred.',
    documents: ['Incorporation Certificate', 'DPIIT Certificate', 'Business Plan', 'Product Demo', 'Founder Details'],
    applyUrl: 'https://t-hub.co/',
    benefits: 'World-class incubation facility, mentorship from industry experts, investor connections, access to corporates, networking events, global market access.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== ANDHRA PRADESH ==========
  {
    name: 'Andhra Pradesh MSME Support Scheme',
    slug: 'andhra-pradesh-msme-support',
    shortDescription: 'Financial and technical support for AP MSMEs',
    description: 'AP MSME Support Scheme provides comprehensive financial and technical assistance to MSMEs. Includes capital subsidy, interest subsidy, and infrastructure support.',
    type: 'state',
    state: 'andhra-pradesh',
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 100000,
    maxAmount: 10000000,
    eligibility: 'MSMEs registered in Andhra Pradesh with Udyam certificate. New units and expansion projects. Minimum investment ₹1 lakh.',
    documents: ['Udyam Certificate', 'Project Report', 'Investment Proof', 'Land Documents', 'Bank Account'],
    applyUrl: 'https://www.apindustries.gov.in/',
    benefits: '25% capital investment subsidy, interest subsidy 5% for 5 years, stamp duty reimbursement, power subsidy, employment generation incentive.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== KERALA ==========
  {
    name: 'Kerala Startup Mission - Seed Fund',
    slug: 'kerala-startup-mission',
    shortDescription: 'Seed funding and support for Kerala startups',
    description: 'Kerala Startup Mission provides comprehensive support ecosystem for startups including seed funding, incubation, mentorship, and market access. Focus on innovation and technology.',
    type: 'state',
    state: 'kerala',
    sector: ['Technology', 'Innovation', 'Services'],
    minAmount: 0,
    maxAmount: 5000000,
    eligibility: 'Startups incorporated in Kerala. DPIIT recognition preferred. Innovative business model. Age less than 7 years from incorporation.',
    documents: ['Incorporation Certificate', 'DPIIT Certificate', 'Business Plan', 'Pitch Deck', 'Founder KYC'],
    applyUrl: 'https://startupmission.kerala.gov.in/',
    benefits: 'Seed funding up to ₹50 lakh, incubation support, mentorship, co-working spaces, investor connects, international exposure programs.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== MADHYA PRADESH ==========
  {
    name: 'Madhya Pradesh MSME Loan Scheme',
    slug: 'madhya-pradesh-msme-loan',
    shortDescription: 'Financial assistance for MP MSMEs',
    description: 'MP Financial Corporation provides term loans and working capital to MSMEs at subsidized rates. Focus on promoting industrial development in backward regions.',
    type: 'state',
    state: 'madhya-pradesh',
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 100000,
    maxAmount: 10000000,
    eligibility: 'MSMEs in Madhya Pradesh with Udyam certificate. Operating for minimum 1 year. Good credit history.',
    documents: ['Udyam Certificate', 'Aadhar Card', 'PAN Card', 'Bank Statements', 'Financial Statements', 'MP Domicile'],
    applyUrl: 'https://www.mpfc.in/',
    benefits: 'Subsidized interest rates, loans up to ₹1 crore, flexible tenure, technical assistance, marketing support.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== HARYANA ==========
  {
    name: 'Haryana Enterprise Promotion Policy',
    slug: 'haryana-enterprise-promotion',
    shortDescription: 'Investment subsidy and incentives in Haryana',
    description: 'Haryana Enterprise Promotion Policy provides capital investment subsidy, interest subsidy, and various incentives to promote MSMEs and industrial development.',
    type: 'state',
    state: 'haryana',
    sector: ['Manufacturing', 'Services'],
    minAmount: 5000000,
    maxAmount: 0,
    eligibility: 'New manufacturing units or expansion in Haryana. Minimum investment ₹50 lakh. Must create employment.',
    documents: ['Project Report', 'Land Documents', 'Udyam Certificate', 'Investment Proof', 'Employment Details'],
    applyUrl: 'https://haryanaindustries.gov.in/',
    benefits: '30% capital subsidy, interest subsidy 5%, stamp duty exemption, employment generation subsidy, power tariff subsidy.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== PUNJAB ==========
  {
    name: 'Punjab MSME Loan and Subsidy Scheme',
    slug: 'punjab-msme-loan-subsidy',
    shortDescription: 'Comprehensive MSME support in Punjab',
    description: 'Punjab Financial Corporation provides term loans, working capital, and capital subsidy to MSMEs. Focus on promoting industrial growth and employment generation.',
    type: 'state',
    state: 'punjab',
    sector: ['Manufacturing', 'Services', 'Agriculture'],
    minAmount: 100000,
    maxAmount: 10000000,
    eligibility: 'MSMEs in Punjab with Udyam registration. New units and expansion projects eligible.',
    documents: ['Udyam Certificate', 'Project Report', 'Punjab Domicile', 'Bank Account', 'Investment Proof'],
    applyUrl: 'https://investpunjab.gov.in/',
    benefits: '25% capital subsidy, interest subsidy, stamp duty exemption, power subsidy, marketing assistance.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== ODISHA ==========
  {
    name: 'Odisha MSME Support and Handloom Scheme',
    slug: 'odisha-msme-handloom',
    shortDescription: 'Support for MSMEs and handloom weavers',
    description: 'Odisha government provides financial assistance, skill training, and marketing support to MSMEs and traditional handloom weavers.',
    type: 'state',
    state: 'odisha',
    sector: ['Manufacturing', 'Handicraft', 'Textile'],
    minAmount: 50000,
    maxAmount: 5000000,
    eligibility: 'MSMEs and artisans in Odisha. Handloom weavers, handicraft artisans, and small manufacturers.',
    documents: ['Udyam Certificate', 'Artisan ID', 'Bank Account', 'Odisha Domicile', 'Skill Certificate'],
    applyUrl: 'https://www.msme.odisha.gov.in/',
    benefits: 'Capital subsidy 30%, interest subsidy, marketing support, design development assistance, training programs.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== ASSAM ==========
  {
    name: 'Assam MSME Development Scheme',
    slug: 'assam-msme-development',
    shortDescription: 'Financial assistance for Assam MSMEs',
    description: 'Assam Financial Corporation provides term loans and working capital to MSMEs. Special focus on tea, bamboo, food processing, and traditional industries.',
    type: 'state',
    state: 'assam',
    sector: ['Manufacturing', 'Agriculture', 'Food Processing'],
    minAmount: 100000,
    maxAmount: 8000000,
    eligibility: 'MSMEs in Assam with Udyam certificate. Operating for minimum 1 year. Priority for tea, bamboo, food processing sectors.',
    documents: ['Udyam Certificate', 'Project Report', 'Assam Domicile', 'Bank Statements', 'Land Documents'],
    applyUrl: 'https://industries.assam.gov.in/',
    benefits: 'Subsidized loans up to ₹80 lakh, 25% capital subsidy, interest subsidy, transport subsidy, industrial promotion assistance.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== CHHATTISGARH ==========
  {
    name: 'Chhattisgarh MSME Promotion Scheme',
    slug: 'chhattisgarh-msme-promotion',
    shortDescription: 'Investment subsidy for CG industries',
    description: 'Chhattisgarh Industrial Policy provides capital subsidy, interest subsidy, and tax exemptions to promote MSME development in the state.',
    type: 'state',
    state: 'chhattisgarh',
    sector: ['Manufacturing', 'Services', 'Mining'],
    minAmount: 1000000,
    maxAmount: 0,
    eligibility: 'New manufacturing units in Chhattisgarh. Minimum investment ₹10 lakh. Must create local employment.',
    documents: ['Project Report', 'Udyam Certificate', 'Land Documents', 'Investment Proof', 'Environmental Clearance'],
    applyUrl: 'https://cgindustry.in/',
    benefits: '25-40% capital subsidy based on location, stamp duty exemption, power tariff subsidy, VAT exemption, employment subsidy.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== JHARKHAND ==========
  {
    name: 'Jharkhand MSME Financial Assistance',
    slug: 'jharkhand-msme-financial',
    shortDescription: 'Loans and subsidies for Jharkhand MSMEs',
    description: 'Jharkhand government provides term loans, working capital, and capital subsidy to MSMEs through state financial institutions.',
    type: 'state',
    state: 'jharkhand',
    sector: ['Manufacturing', 'Mining', 'Services'],
    minAmount: 100000,
    maxAmount: 10000000,
    eligibility: 'MSMEs in Jharkhand with Udyam registration. Minimum 1 year operation. Priority for mining, manufacturing sectors.',
    documents: ['Udyam Certificate', 'Project Report', 'Jharkhand Domicile', 'Financial Statements', 'Mining License (if applicable)'],
    applyUrl: 'https://jharkhandindustry.gov.in/',
    benefits: '30% capital subsidy, interest subsidy 5%, stamp duty exemption, VAT deferment, employment generation incentive.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== UTTARAKHAND ==========
  {
    name: 'Uttarakhand MSME Development Scheme',
    slug: 'uttarakhand-msme-development',
    shortDescription: 'Hill state incentives for MSMEs',
    description: 'Uttarakhand provides special incentives for MSMEs in hill regions including capital subsidy, interest subsidy, and transport subsidy.',
    type: 'state',
    state: 'uttarakhand',
    sector: ['Manufacturing', 'Tourism', 'Agriculture'],
    minAmount: 100000,
    maxAmount: 10000000,
    eligibility: 'MSMEs in Uttarakhand, especially hill regions. New units and expansion projects. Focus on eco-friendly and sustainable industries.',
    documents: ['Udyam Certificate', 'Project Report', 'UK Domicile', 'Environmental Compliance', 'Investment Proof'],
    applyUrl: 'https://www.uk.gov.in/',
    benefits: '30% capital subsidy, interest subsidy 5%, transport subsidy, stamp duty exemption, power subsidy, special incentives for hill areas.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== HIMACHAL PRADESH ==========
  {
    name: 'Himachal Pradesh MSME Incentive Scheme',
    slug: 'himachal-pradesh-msme-incentive',
    shortDescription: 'Hill state benefits for HP industries',
    description: 'HP Industrial Policy provides comprehensive incentives including capital subsidy, GST reimbursement, and transport subsidy for MSMEs in hilly terrain.',
    type: 'state',
    state: 'himachal-pradesh',
    sector: ['Manufacturing', 'Tourism', 'Handicraft'],
    minAmount: 500000,
    maxAmount: 0,
    eligibility: 'New manufacturing units in HP. Minimum investment ₹5 lakh. Must operate for minimum 5 years to avail full benefits.',
    documents: ['Project Report', 'Udyam Certificate', 'Land Documents', 'HP Domicile', 'Investment Proof'],
    applyUrl: 'https://admis.hp.nic.in/',
    benefits: '30% capital subsidy, 100% stamp duty exemption, 80% GST reimbursement for 7 years, transport subsidy, electricity duty exemption.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== GOA ==========
  {
    name: 'Goa Startup and MSME Policy',
    slug: 'goa-startup-msme',
    shortDescription: 'Comprehensive support for Goa enterprises',
    description: 'Goa government provides incubation support, seed funding, and various incentives to startups and MSMEs. Focus on technology and tourism sectors.',
    type: 'state',
    state: 'goa',
    sector: ['Technology', 'Tourism', 'Services'],
    minAmount: 0,
    maxAmount: 3000000,
    eligibility: 'Startups and MSMEs registered in Goa. DPIIT recognition preferred for startups. Innovative business models.',
    documents: ['Incorporation Certificate', 'Goa Registration Proof', 'Business Plan', 'DPIIT Certificate (for startups)'],
    applyUrl: 'https://www.goa.gov.in/',
    benefits: 'Seed funding up to ₹30 lakh, incubation support, stamp duty reimbursement, marketing assistance, co-working space subsidy.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== BIHAR ==========
  {
    name: 'Bihar MSME Promotion and Development Scheme',
    slug: 'bihar-msme-promotion',
    shortDescription: 'Financial support for Bihar industries',
    description: 'Bihar Industrial Investment Promotion Policy provides capital subsidy, interest subsidy, and various tax exemptions to promote MSME growth.',
    type: 'state',
    state: 'bihar',
    sector: ['Manufacturing', 'Agriculture', 'Food Processing'],
    minAmount: 500000,
    maxAmount: 0,
    eligibility: 'New manufacturing units in Bihar. Minimum fixed capital investment ₹5 lakh. Must generate local employment.',
    documents: ['Project Report', 'Udyam Certificate', 'Land Documents', 'Bihar Domicile', 'Investment Details'],
    applyUrl: 'https://www.startup.bihar.gov.in/',
    benefits: '25% capital subsidy (up to ₹25 lakh), interest subsidy 5%, stamp duty exemption, land subsidy, employment generation incentive.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },

  // ========== DELHI ==========
  {
    name: 'Delhi MSME Support Scheme',
    slug: 'delhi-msme-support',
    shortDescription: 'Financial assistance for Delhi MSMEs',
    description: 'Delhi government provides various schemes for MSMEs including loans, subsidies, and facilitation services through Delhi Financial Corporation.',
    type: 'state',
    state: 'delhi',
    sector: ['Manufacturing', 'Services', 'Trading'],
    minAmount: 100000,
    maxAmount: 10000000,
    eligibility: 'MSMEs registered in Delhi with Udyam certificate. Operating for minimum 1 year. All sectors covered.',
    documents: ['Udyam Certificate', 'Delhi Address Proof', 'Bank Statements', 'Financial Statements', 'GST Registration'],
    applyUrl: 'https://delhi.gov.in/',
    benefits: 'Term loans up to ₹1 crore, working capital support, subsidized interest rates, quick processing, technical assistance.',
    isActive: true,
    isFeatured: false,
    isSponsored: false,
    sponsoredUntil: null,
    viewCount: 0,
  },
]

export const LOAN_PROVIDERS = [
  {
    name: 'Lendingkart',
    slug: 'lendingkart',
    provider: 'Lendingkart',
    providerLogo: 'https://lendingkart.com/logo.png',
    type: 'business',
    minAmount: 100000,
    maxAmount: 10000000,
    interestRateMin: 12,
    interestRateMax: 24,
    tenure: '12-36 months',
    eligibility: 'Business must be registered and operating for at least 12 months. Annual turnover minimum ₹10 lakh. GST registration required. Credit score above 650 preferred.',
    documents: ['Aadhar Card', 'PAN Card', 'GST Registration', 'Business Registration', 'Bank Statement (last 6 months)', 'ITR (last 2 years)', 'Office Address Proof'],
    features: ['Collateral-free loans available', 'Quick approval within 48 hours', 'No hidden charges', 'Flexible repayment options', 'Online application process'],
    affiliateUrl: 'https://lendingkart.com',
    isSponsored: true,
    viewCount: 0,
  },
  {
    name: 'NeoGrowth',
    slug: 'neogrowth',
    provider: 'NeoGrowth',
    providerLogo: 'https://neogrowth.in/logo.png',
    type: 'business',
    minAmount: 100000,
    maxAmount: 15000000,
    interestRateMin: 15,
    interestRateMax: 22,
    tenure: '12-48 months',
    eligibility: 'Business must be registered and operating for at least 18 months. Annual turnover minimum ₹50 lakh. GST registration required. Positive cash flow required.',
    documents: ['Aadhar Card', 'PAN Card', 'GST Registration', 'Business Registration', 'Bank Statement (last 12 months)', 'ITR (last 2 years)', 'Office Address Proof', 'Photos of Business Premises'],
    features: ['No collateral required for eligible businesses', 'Flexible EMI options', 'Quick processing time 3-5 days', 'Dedicated relationship manager', 'No prepayment charges'],
    affiliateUrl: 'https://neogrowth.in',
    isSponsored: true,
    viewCount: 0,
  },
  {
    name: 'Indifi',
    slug: 'indifi',
    provider: 'Indifi',
    providerLogo: 'https://indifi.com/logo.png',
    type: 'business',
    minAmount: 50000,
    maxAmount: 5000000,
    interestRateMin: 18,
    interestRateMax: 26,
    tenure: '12-36 months',
    eligibility: 'Business must be registered and operating for at least 12 months. Annual turnover minimum ₹10 lakh. GST registration required. Good repayment track record.',
    documents: ['Aadhar Card', 'PAN Card', 'GST Registration', 'Business Registration', 'Bank Statement (last 6 months)', 'ITR (last 2 years)', 'Office Address Proof'],
    features: ['Data-driven loan decisions', 'Quick approval within 2-3 days', 'Minimal documentation', 'Flexible EMI options', 'No collateral required'],
    affiliateUrl: 'https://indifi.com',
    isSponsored: true,
    viewCount: 0,
  },
  {
    name: 'FlexiLoans',
    slug: 'flexiloans',
    provider: 'FlexiLoans',
    providerLogo: 'https://flexiloans.com/logo.png',
    type: 'business',
    minAmount: 75000,
    maxAmount: 7500000,
    interestRateMin: 15,
    interestRateMax: 24,
    tenure: '12-60 months',
    eligibility: 'Business must be registered and operating for at least 12 months. Annual turnover minimum ₹20 lakh. GST registration required. Stable business required.',
    documents: ['Aadhar Card', 'PAN Card', 'GST Registration', 'Business Registration', 'Bank Statement (last 12 months)', 'ITR (last 3 years)', 'Business Plan', 'Office Address Proof'],
    features: ['Collateral-free options available', 'Quick approval within 24-48 hours', 'No processing fees', 'Flexible repayment schedules', 'Working capital and term loans'],
    affiliateUrl: 'https://flexiloans.com',
    isSponsored: true,
    viewCount: 0,
  },
  {
    name: 'Tata Capital SME Loan',
    slug: 'tata-capital-sme-loan',
    provider: 'Tata Capital',
    providerLogo: 'https://tatacapital.com/logo.png',
    type: 'business',
    minAmount: 50000,
    maxAmount: 5000000,
    interestRateMin: 10,
    interestRateMax: 16,
    tenure: '12-60 months',
    eligibility: 'Business must be registered and operating for at least 12 months. Annual turnover minimum ₹20 lakh. GST registration required. Strong financial statements required.',
    documents: ['Aadhar Card', 'PAN Card', 'GST Registration', 'Audited Financial Statements (last 2 years)', 'ITR (last 3 years)', 'Bank Statements (last 1 year)', 'Proof of Business Continuity'],
    features: ['Trusted Tata brand', 'Competitive interest rates', 'Quick processing within 5-7 days', 'Collateral-free options available', 'Dedicated relationship manager'],
    affiliateUrl: 'https://www.tatacapital.com/sme',
    isSponsored: true,
    viewCount: 0,
  },
  {
    name: 'HDFC Bank Business Loan',
    slug: 'hdfc-business-loan',
    provider: 'HDFC Bank',
    providerLogo: 'https://hdfcbank.com/logo.png',
    type: 'business',
    minAmount: 50000,
    maxAmount: 5000000,
    interestRateMin: 9.5,
    interestRateMax: 14,
    tenure: '12-60 months',
    eligibility: 'Business must be registered and operating for at least 12 months. Annual turnover minimum ₹20 lakh. GST registration required. Good credit history mandatory.',
    documents: ['Aadhar Card', 'PAN Card', 'GST Registration', 'Audited Financial Statements (last 2 years)', 'ITR (last 3 years)', 'Bank Statements (last 1 year)', 'Proof of Business Continuity'],
    features: ['Lowest interest rates starting from 9.5%', 'Quick approval within 3-5 days', 'No hidden charges', 'Flexible repayment options', 'Collateral-free options available'],
    affiliateUrl: 'https://www.hdfcbank.com/business-loan',
    isSponsored: true,
    viewCount: 0,
  },
  {
    name: 'SBI Mudra Loan',
    slug: 'sbi-mudra-loan',
    provider: 'State Bank of India',
    providerLogo: 'https://sbi.co.in/logo.png',
    type: 'mudra',
    minAmount: 50000,
    maxAmount: 500000,
    interestRateMin: 8.4,
    interestRateMax: 12.25,
    tenure: '36-60 months',
    eligibility: 'Business must be registered and operating for at least 12 months. Annual turnover minimum ₹10 lakh. GST registration required. Good credit score above 650 preferred.',
    documents: ['Aadhar Card', 'PAN Card', 'GST Registration', 'Business Registration', 'Bank Statement (last 6 months)', 'ITR (last 2 years)', 'Office Address Proof', 'Photograph'],
    features: ['Official government scheme', 'Interest rate starting from 8.40%', 'Collateral-free loans up to ₹5 lakh', 'Quick processing within 7-10 days', 'No processing fees', 'Wide network of SBI branches'],
    affiliateUrl: 'https://sbi.co.in/mudra-loans',
    isSponsored: true,
    viewCount: 0,
  },
  {
    name: 'Ugro Capital Business Loan',
    slug: 'ugro-capital',
    provider: 'Ugro Capital',
    providerLogo: 'https://ugrocapital.com/logo.png',
    type: 'business',
    minAmount: 1000000,
    maxAmount: 50000000,
    interestRateMin: 14,
    interestRateMax: 22,
    tenure: '12-48 months',
    eligibility: 'Business must be registered and operating for at least 24 months. Annual turnover minimum ₹2 crore. GST registration mandatory. Strong financial statements and good credit history required.',
    documents: ['Aadhar Card', 'PAN Card', 'GST Registration', 'Udyam Registration', 'Audited Financial Statements (last 2 years)', 'ITR (last 3 years)', 'Bank Statements (last 12 months)', 'Business Registration Certificate', 'Office Address Proof'],
    features: ['Large loan amounts ₹10L-₹5Cr', 'Collateral-free options available', 'Quick approval within 3-7 days', 'Dedicated relationship manager', 'Flexible repayment tenure', 'Digital-first loan process'],
    affiliateUrl: 'https://www.ugrocapital.com',
    isSponsored: true,
    viewCount: 0,
  },
]
