import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { Pool } from 'pg'
import { config } from 'dotenv'

// Load environment variables
config({ path: '.env.local' })

// Create connection pool
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  database: 'postgres',
})

const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

// Comprehensive list of CA firms and MSME consultants across major Indian cities
const CONSULTANTS = [
  // Mumbai - Maharashtra
  {
    name: 'Rajesh Kumar',
    firmName: 'RK Associates',
    slug: 'rk-associates-chartered-accountants-mumbai',
    designation: 'Chartered Accountant',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['MSME Registration', 'Udyam Registration', 'GST Filing', 'Tax Audit', 'Loan Documentation', 'Subsidy Consultation'],
    phone: '+91-9876543210',
    email: 'rajesh@rkassociates.com',
    website: 'https://rkassociates.com',
    bio: 'Experienced CA with 15+ years in MSME consulting. Helped 500+ businesses secure government loans and subsidies. Expert in Mudra Loan, CGTMSE, and Stand Up India schemes.',
    experience: 15,
    reviewCount: 127,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Neha Joshi',
    firmName: 'Joshi & Partners CA',
    slug: 'joshi-partners-ca-mumbai-andheri',
    designation: 'Chartered Accountant',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['Company Registration', 'MSME Loans', 'Income Tax Filing', 'GST Registration', 'Startup India Registration'],
    phone: '+91-9876543220',
    email: 'neha@joshipartners.in',
    website: 'https://joshipartners.in',
    bio: 'Mumbai-based CA firm specializing in startup and MSME advisory. 200+ successful loan applications processed. Expert in Startup India benefits.',
    experience: 12,
    reviewCount: 89,
    rating: 4.7,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },
  {
    name: 'Suresh Patil',
    firmName: 'Patil Financial Consultants',
    slug: 'patil-financial-consultants-mumbai-bandra',
    designation: 'Financial Consultant',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['Working Capital Loans', 'MSME Registration', 'Business Loans', 'Credit Guarantee Scheme', 'Subsidy Claims'],
    phone: '+91-9876543221',
    email: 'suresh@patilfinancial.com',
    bio: 'Specialized in working capital and business loans for MSMEs. ₹100Cr+ loans facilitated. Quick processing guaranteed.',
    experience: 18,
    reviewCount: 156,
    rating: 4.9,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Delhi NCR
  {
    name: 'Priya Sharma',
    firmName: 'Sharma & Co. Chartered Accountants',
    slug: 'sharma-co-chartered-accountants-delhi',
    designation: 'Chartered Accountant',
    city: 'Delhi',
    state: 'Delhi',
    services: ['Startup Registration', 'Government Schemes', 'Business Planning', 'Financial Advisory', 'MSME Loans', 'Tax Planning'],
    phone: '+91-9876543211',
    email: 'priya@sharmaco.in',
    website: 'https://sharmaco.in',
    bio: 'Specialized in helping startups navigate government schemes and secure funding. Expert in PM Mudra, Stand Up India, and CGTMSE schemes. 300+ successful applications.',
    experience: 10,
    reviewCount: 98,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Arun Gupta',
    firmName: 'Gupta & Associates',
    slug: 'gupta-associates-ca-delhi-connaught-place',
    designation: 'Chartered Accountant',
    city: 'Delhi',
    state: 'Delhi',
    services: ['Udyam Registration', 'GST Services', 'Tax Audit', 'MSME Compliance', 'Loan Documentation'],
    phone: '+91-9876543222',
    email: 'arun@guptaassociates.in',
    website: 'https://guptaassociates.in',
    bio: 'Delhi-based CA firm with 20+ years experience. Comprehensive MSME services from registration to compliance. Trusted by 1000+ businesses.',
    experience: 20,
    reviewCount: 234,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Kavita Verma',
    firmName: 'Verma Tax Consultants',
    slug: 'verma-tax-consultants-noida',
    designation: 'Tax Consultant',
    city: 'Noida',
    state: 'Uttar Pradesh',
    services: ['Tax Filing', 'GST Registration', 'MSME Registration', 'Startup Advisory', 'Business Compliance'],
    phone: '+91-9876543223',
    email: 'kavita@vermatax.in',
    bio: 'Noida-based tax consultant specializing in MSME and startup taxation. Expert in UP state schemes and central government subsidies.',
    experience: 8,
    reviewCount: 67,
    rating: 4.6,
    isPremium: false,
    tier: 'featured',
    isVerified: true,
  },
  {
    name: 'Rohit Malhotra',
    firmName: 'Malhotra & Sons CA',
    slug: 'malhotra-sons-ca-gurgaon',
    designation: 'Chartered Accountant',
    city: 'Gurgaon',
    state: 'Haryana',
    services: ['Company Audit', 'MSME Loans', 'Tax Planning', 'Business Advisory', 'Compliance Services'],
    phone: '+91-9876543224',
    email: 'rohit@malhotraca.com',
    website: 'https://malhotraca.com',
    bio: 'Gurgaon-based CA firm serving corporate and MSME clients. Expertise in Haryana state schemes and startup ecosystem.',
    experience: 14,
    reviewCount: 112,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Bangalore - Karnataka
  {
    name: 'Sunita Reddy',
    firmName: 'Reddy & Associates CA',
    slug: 'reddy-associates-ca-bangalore-koramangala',
    designation: 'Chartered Accountant',
    city: 'Bangalore',
    state: 'Karnataka',
    services: ['Udyam Registration', 'Startup India', 'GST Filing', 'Export Documentation', 'Tech Startup Advisory'],
    phone: '+91-9876543213',
    email: 'sunita@reddyca.com',
    website: 'https://reddyca.com',
    bio: 'Karnataka MSME specialist with expertise in tech startup schemes. 8+ years experience. Expert in Karnataka state subsidies and IT/ITES benefits.',
    experience: 8,
    reviewCount: 78,
    rating: 4.6,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },
  {
    name: 'Kiran Rao',
    firmName: 'Rao Financial Services',
    slug: 'rao-financial-services-bangalore-whitefield',
    designation: 'Financial Advisor',
    city: 'Bangalore',
    state: 'Karnataka',
    services: ['Business Loans', 'Working Capital', 'MSME Registration', 'Subsidy Claims', 'Investment Advisory'],
    phone: '+91-9876543225',
    email: 'kiran@raofinancial.in',
    bio: 'Bangalore Whitefield-based financial advisor. Specialized in tech startup and manufacturing MSME financing. ₹75Cr+ loans facilitated.',
    experience: 11,
    reviewCount: 93,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Deepa Krishnamurthy',
    firmName: 'Krishnamurthy & Co',
    slug: 'krishnamurthy-co-ca-bangalore-indiranagar',
    designation: 'Chartered Accountant',
    city: 'Bangalore',
    state: 'Karnataka',
    services: ['Tax Audit', 'GST Compliance', 'MSME Advisory', 'Startup Registration', 'Annual Compliance'],
    phone: '+91-9876543226',
    email: 'deepa@krishnamurthyco.com',
    bio: 'Indiranagar-based CA firm with focus on compliance and advisory for MSMEs and startups. Trusted partner for 500+ businesses.',
    experience: 15,
    reviewCount: 145,
    rating: 4.9,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Ahmedabad - Gujarat
  {
    name: 'Amit Patel',
    firmName: 'Patel Financial Services',
    slug: 'patel-financial-services-ahmedabad',
    designation: 'Financial Advisor',
    city: 'Ahmedabad',
    state: 'Gujarat',
    services: ['MSME Loans', 'Credit Guarantee', 'Working Capital', 'Subsidy Claims', 'Business Registration'],
    phone: '+91-9876543212',
    email: 'amit@patelfinancial.com',
    website: 'https://patelfinancial.com',
    bio: 'Gujarat-based MSME expert with deep knowledge of state and central schemes. ₹50Cr+ loans facilitated. Expert in Gujarat Industrial Policy benefits.',
    experience: 12,
    reviewCount: 167,
    rating: 4.9,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Hemant Shah',
    firmName: 'Shah & Shah CA',
    slug: 'shah-shah-chartered-accountants-ahmedabad',
    designation: 'Chartered Accountant',
    city: 'Ahmedabad',
    state: 'Gujarat',
    services: ['Tax Planning', 'MSME Registration', 'Audit Services', 'GST Filing', 'Business Advisory'],
    phone: '+91-9876543227',
    email: 'hemant@shahshahca.com',
    website: 'https://shahshahca.com',
    bio: 'Leading CA firm in Ahmedabad with 25+ years legacy. Comprehensive services for MSMEs in textiles, chemicals, and manufacturing sectors.',
    experience: 25,
    reviewCount: 289,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Nisha Mehta',
    firmName: 'Mehta Business Solutions',
    slug: 'mehta-business-solutions-surat',
    designation: 'Business Consultant',
    city: 'Surat',
    state: 'Gujarat',
    services: ['Textile MSME Loans', 'Diamond Industry Advisory', 'GST Services', 'Export Benefits', 'Subsidy Applications'],
    phone: '+91-9876543228',
    email: 'nisha@mehtasolutions.in',
    bio: 'Surat-based consultant specializing in textile and diamond industry MSMEs. Expert in Gujarat state schemes for traditional industries.',
    experience: 10,
    reviewCount: 87,
    rating: 4.7,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Pune - Maharashtra
  {
    name: 'Vikram Singh',
    firmName: 'Singh & Associates',
    slug: 'singh-associates-ca-pune-shivajinagar',
    designation: 'Chartered Accountant',
    city: 'Pune',
    state: 'Maharashtra',
    services: ['Business Registration', 'Scheme Advisory', 'Loan Documentation', 'Compliance', 'Tax Services'],
    phone: '+91-9876543214',
    email: 'vikram@singhassociates.in',
    website: 'https://singhassociates.in',
    bio: 'Pune-based consultant specializing in manufacturing MSMEs. Quick loan approvals guaranteed. 15+ years in MSME ecosystem.',
    experience: 15,
    reviewCount: 134,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Meera Kulkarni',
    firmName: 'Kulkarni Financial Advisors',
    slug: 'kulkarni-financial-advisors-pune-hinjewadi',
    designation: 'Financial Advisor',
    city: 'Pune',
    state: 'Maharashtra',
    services: ['IT MSME Advisory', 'Startup Funding', 'Working Capital', 'Business Loans', 'Tax Planning'],
    phone: '+91-9876543229',
    email: 'meera@kulkarniadvisors.com',
    bio: 'Hinjewadi-based advisor specializing in IT and tech MSMEs. Expert in Maharashtra IT policy benefits and software export subsidies.',
    experience: 9,
    reviewCount: 76,
    rating: 4.6,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Hyderabad - Telangana
  {
    name: 'Anjali Reddy',
    firmName: 'Reddy Tax & Business Advisors',
    slug: 'reddy-tax-advisors-hyderabad-banjara-hills',
    designation: 'Chartered Accountant',
    city: 'Hyderabad',
    state: 'Telangana',
    services: ['MSME Registration', 'Subsidy Claims', 'Tax Planning', 'Audit Services', 'T-Hub Startup Advisory'],
    phone: '+91-9876543215',
    email: 'anjali@reddytax.com',
    website: 'https://reddytax.com',
    bio: 'Telangana MSME expert with strong track record in subsidy claims. 200+ successful TS-iPASS applications. Expert in Telangana state incentives.',
    experience: 11,
    reviewCount: 112,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Srinivas Rao',
    firmName: 'Rao & Company CA',
    slug: 'rao-company-ca-hyderabad-hitec-city',
    designation: 'Chartered Accountant',
    city: 'Hyderabad',
    state: 'Telangana',
    services: ['IT Company Advisory', 'GST Services', 'MSME Loans', 'Compliance', 'Business Registration'],
    phone: '+91-9876543230',
    email: 'srinivas@raoca.in',
    bio: 'HITEC City-based CA serving IT and pharma MSMEs. Deep expertise in Telangana industrial policy and TS-iPASS scheme.',
    experience: 13,
    reviewCount: 98,
    rating: 4.7,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Chennai - Tamil Nadu
  {
    name: 'Lakshmi Narayanan',
    firmName: 'Narayanan & Associates CA',
    slug: 'narayanan-associates-ca-chennai-t-nagar',
    designation: 'Chartered Accountant',
    city: 'Chennai',
    state: 'Tamil Nadu',
    services: ['MSME Registration', 'Tax Audit', 'GST Filing', 'Business Loans', 'Export Documentation'],
    phone: '+91-9876543231',
    email: 'lakshmi@narayananassociates.in',
    website: 'https://narayananassociates.in',
    bio: 'Chennai-based CA firm with 20+ years experience. Expert in Tamil Nadu state schemes including NEEDS and TUFIDCO benefits.',
    experience: 20,
    reviewCount: 189,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Ramesh Subramanian',
    firmName: 'Subramanian Financial Services',
    slug: 'subramanian-financial-chennai-anna-nagar',
    designation: 'Financial Consultant',
    city: 'Chennai',
    state: 'Tamil Nadu',
    services: ['Manufacturing Loans', 'MSME Subsidy', 'Working Capital', 'Business Advisory', 'Compliance'],
    phone: '+91-9876543232',
    email: 'ramesh@subramanianfinancial.com',
    bio: 'Anna Nagar-based consultant specializing in manufacturing MSMEs. Expert in auto ancillary and textile industry financing.',
    experience: 16,
    reviewCount: 134,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Preethi Venkatesh',
    firmName: 'Venkatesh Tax Consultants',
    slug: 'venkatesh-tax-consultants-coimbatore',
    designation: 'Tax Consultant',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    services: ['Tax Planning', 'MSME Registration', 'Textile Industry Advisory', 'GST Services', 'Loan Documentation'],
    phone: '+91-9876543233',
    email: 'preethi@venkateshtax.in',
    bio: 'Coimbatore-based tax consultant with expertise in textile MSMEs. Specialized in pump and motor manufacturing sector advisory.',
    experience: 9,
    reviewCount: 67,
    rating: 4.6,
    isPremium: false,
    tier: 'featured',
    isVerified: true,
  },

  // Kolkata - West Bengal
  {
    name: 'Abhijit Banerjee',
    firmName: 'Banerjee & Co. CA',
    slug: 'banerjee-co-chartered-accountants-kolkata',
    designation: 'Chartered Accountant',
    city: 'Kolkata',
    state: 'West Bengal',
    services: ['MSME Registration', 'Tax Audit', 'GST Filing', 'Business Loans', 'Subsidy Applications'],
    phone: '+91-9876543234',
    email: 'abhijit@banerjeeca.com',
    website: 'https://banerjeeca.com',
    bio: 'Kolkata-based CA firm with 18+ years experience. Expert in West Bengal Incentive Scheme (WBIS) and Shilpa Sathi benefits.',
    experience: 18,
    reviewCount: 156,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Ritu Ghosh',
    firmName: 'Ghosh Financial Advisors',
    slug: 'ghosh-financial-advisors-kolkata-salt-lake',
    designation: 'Financial Advisor',
    city: 'Kolkata',
    state: 'West Bengal',
    services: ['Business Loans', 'Working Capital', 'MSME Advisory', 'Tea Industry Loans', 'Export Benefits'],
    phone: '+91-9876543235',
    email: 'ritu@ghoshadvisors.in',
    bio: 'Salt Lake-based advisor specializing in traditional industries. Expert in jute, tea, and handloom MSME financing and subsidies.',
    experience: 12,
    reviewCount: 89,
    rating: 4.7,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Jaipur - Rajasthan
  {
    name: 'Mahesh Agarwal',
    firmName: 'Agarwal & Sons CA',
    slug: 'agarwal-sons-chartered-accountants-jaipur',
    designation: 'Chartered Accountant',
    city: 'Jaipur',
    state: 'Rajasthan',
    services: ['MSME Registration', 'Handicraft Industry Advisory', 'Tax Services', 'Business Loans', 'Gem & Jewelry MSME'],
    phone: '+91-9876543236',
    email: 'mahesh@agarwalca.com',
    website: 'https://agarwalca.com',
    bio: 'Jaipur-based CA firm specializing in handicraft and gem & jewelry MSMEs. Expert in RIICO benefits and Rajasthan investment subsidies.',
    experience: 22,
    reviewCount: 178,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Pooja Sharma',
    firmName: 'Sharma Business Consultants',
    slug: 'sharma-business-consultants-jaipur',
    designation: 'Business Consultant',
    city: 'Jaipur',
    state: 'Rajasthan',
    services: ['Tourism MSME Advisory', 'Handicraft Subsidies', 'GST Services', 'Business Registration', 'Loan Documentation'],
    phone: '+91-9876543237',
    email: 'pooja@sharmabusiness.in',
    bio: 'Jaipur consultant specializing in tourism and handicraft sectors. Expert in Rajasthan state schemes for traditional industries.',
    experience: 8,
    reviewCount: 56,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },

  // Lucknow - Uttar Pradesh
  {
    name: 'Vivek Srivastava',
    firmName: 'Srivastava & Associates',
    slug: 'srivastava-associates-ca-lucknow',
    designation: 'Chartered Accountant',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    services: ['MSME Registration', 'ODOP Advisory', 'Tax Audit', 'Business Loans', 'UP State Schemes'],
    phone: '+91-9876543238',
    email: 'vivek@srivastavaca.com',
    website: 'https://srivastavaca.com',
    bio: 'Lucknow-based CA firm with expertise in UP MSME schemes. Specialized in One District One Product (ODOP) scheme applications.',
    experience: 14,
    reviewCount: 123,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    name: 'Anita Mishra',
    firmName: 'Mishra Tax Services',
    slug: 'mishra-tax-services-lucknow',
    designation: 'Tax Consultant',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    services: ['Tax Planning', 'GST Services', 'MSME Advisory', 'Chikankari Industry Loans', 'Business Compliance'],
    phone: '+91-9876543239',
    email: 'anita@mishratax.in',
    bio: 'Lucknow-based tax consultant with focus on traditional industries. Expert in Chikankari and embroidery MSME financing.',
    experience: 10,
    reviewCount: 78,
    rating: 4.6,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Indore - Madhya Pradesh
  {
    name: 'Rakesh Jain',
    firmName: 'Jain & Company CA',
    slug: 'jain-company-chartered-accountants-indore',
    designation: 'Chartered Accountant',
    city: 'Indore',
    state: 'Madhya Pradesh',
    services: ['MSME Registration', 'Tax Audit', 'Business Loans', 'Pharma MSME Advisory', 'GST Services'],
    phone: '+91-9876543240',
    email: 'rakesh@jainca.com',
    website: 'https://jainca.com',
    bio: 'Indore-based CA firm with 16+ years experience. Expert in MP state incentives and pharmaceutical MSME sector advisory.',
    experience: 16,
    reviewCount: 145,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Chandigarh - Punjab/Haryana
  {
    name: 'Gurpreet Singh',
    firmName: 'Singh Financial Services',
    slug: 'singh-financial-services-chandigarh',
    designation: 'Financial Advisor',
    city: 'Chandigarh',
    state: 'Chandigarh',
    services: ['MSME Loans', 'Agro Industry Advisory', 'Business Registration', 'Working Capital', 'Punjab State Schemes'],
    phone: '+91-9876543241',
    email: 'gurpreet@singhfinancial.in',
    bio: 'Chandigarh-based advisor serving Punjab and Haryana MSMEs. Expert in agro-processing and food industry financing.',
    experience: 13,
    reviewCount: 98,
    rating: 4.7,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Kochi - Kerala
  {
    name: 'Thomas Mathew',
    firmName: 'Mathew & Associates CA',
    slug: 'mathew-associates-ca-kochi',
    designation: 'Chartered Accountant',
    city: 'Kochi',
    state: 'Kerala',
    services: ['MSME Registration', 'Export Advisory', 'Spice Industry Loans', 'Tax Services', 'Business Compliance'],
    phone: '+91-9876543242',
    email: 'thomas@mathewca.com',
    website: 'https://mathewca.com',
    bio: 'Kochi-based CA firm specializing in export-oriented MSMEs. Expert in spice, coir, and seafood industry financing.',
    experience: 17,
    reviewCount: 134,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Bhubaneswar - Odisha
  {
    name: 'Subhash Mohanty',
    firmName: 'Mohanty Business Advisors',
    slug: 'mohanty-business-advisors-bhubaneswar',
    designation: 'Business Consultant',
    city: 'Bhubaneswar',
    state: 'Odisha',
    services: ['MSME Registration', 'Handicraft Advisory', 'Mining MSME Loans', 'State Incentives', 'Business Loans'],
    phone: '+91-9876543243',
    email: 'subhash@mohantyadvisors.in',
    bio: 'Bhubaneswar-based consultant with expertise in Odisha state schemes. Specialized in handloom, handicraft, and mineral-based MSMEs.',
    experience: 11,
    reviewCount: 67,
    rating: 4.6,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Nagpur - Maharashtra
  {
    name: 'Anil Deshmukh',
    firmName: 'Deshmukh & Partners CA',
    slug: 'deshmukh-partners-ca-nagpur',
    designation: 'Chartered Accountant',
    city: 'Nagpur',
    state: 'Maharashtra',
    services: ['MSME Registration', 'Orange Processing Loans', 'Tax Audit', 'Business Advisory', 'GST Services'],
    phone: '+91-9876543244',
    email: 'anil@deshmukhca.com',
    bio: 'Nagpur-based CA firm with focus on agro-processing MSMEs. Expert in MIHAN SEZ benefits and Vidarbha region schemes.',
    experience: 14,
    reviewCount: 89,
    rating: 4.7,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Vadodara - Gujarat
  {
    name: 'Jayesh Desai',
    firmName: 'Desai Financial Consultants',
    slug: 'desai-financial-consultants-vadodara',
    designation: 'Financial Consultant',
    city: 'Vadodara',
    state: 'Gujarat',
    services: ['MSME Loans', 'Chemical Industry Advisory', 'Working Capital', 'Gujarat State Schemes', 'Business Registration'],
    phone: '+91-9876543245',
    email: 'jayesh@desaifinancial.in',
    bio: 'Vadodara-based consultant specializing in chemical and petrochemical MSMEs. Expert in Gujarat Industrial Policy benefits.',
    experience: 12,
    reviewCount: 76,
    rating: 4.6,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Visakhapatnam - Andhra Pradesh
  {
    name: 'Venkat Rao',
    firmName: 'Rao & Associates CA',
    slug: 'rao-associates-ca-visakhapatnam',
    designation: 'Chartered Accountant',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    services: ['MSME Registration', 'Port-based Industry Loans', 'Tax Services', 'AP State Schemes', 'Export Advisory'],
    phone: '+91-9876543246',
    email: 'venkat@raoca.in',
    website: 'https://raoca.in',
    bio: 'Vizag-based CA firm with expertise in port-based and steel industry MSMEs. Specialized in AP industrial incentives.',
    experience: 15,
    reviewCount: 98,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Patna - Bihar
  {
    name: 'Rajiv Kumar',
    firmName: 'Kumar Tax Consultants',
    slug: 'kumar-tax-consultants-patna',
    designation: 'Tax Consultant',
    city: 'Patna',
    state: 'Bihar',
    services: ['MSME Registration', 'Food Processing Loans', 'Tax Planning', 'Bihar State Schemes', 'GST Services'],
    phone: '+91-9876543247',
    email: 'rajiv@kumartax.in',
    bio: 'Patna-based consultant with focus on food processing and agro-based MSMEs. Expert in Bihar Industrial Investment Promotion Policy.',
    experience: 10,
    reviewCount: 56,
    rating: 4.5,
    isPremium: false,
    tier: 'featured',
    isVerified: true,
  },

  // Ranchi - Jharkhand
  {
    name: 'Santosh Prasad',
    firmName: 'Prasad Business Solutions',
    slug: 'prasad-business-solutions-ranchi',
    designation: 'Business Consultant',
    city: 'Ranchi',
    state: 'Jharkhand',
    services: ['MSME Registration', 'Mining Sector Advisory', 'Business Loans', 'State Incentives', 'Tax Services'],
    phone: '+91-9876543248',
    email: 'santosh@prasadsolutions.in',
    bio: 'Ranchi-based consultant specializing in mineral-based MSMEs. Expert in Jharkhand Industrial Policy and tribal area incentives.',
    experience: 9,
    reviewCount: 45,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },

  // Guwahati - Assam
  {
    name: 'Dipak Barua',
    firmName: 'Barua & Associates CA',
    slug: 'barua-associates-ca-guwahati',
    designation: 'Chartered Accountant',
    city: 'Guwahati',
    state: 'Assam',
    services: ['MSME Registration', 'Tea Industry Loans', 'NER Subsidies', 'Tax Audit', 'Export Benefits'],
    phone: '+91-9876543249',
    email: 'dipak@baruaca.com',
    bio: 'Guwahati-based CA firm with expertise in North East special incentives. Specialized in tea, bamboo, and handloom MSMEs.',
    experience: 14,
    reviewCount: 78,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Thiruvananthapuram - Kerala
  {
    name: 'Rajan Nair',
    firmName: 'Nair Financial Services',
    slug: 'nair-financial-services-thiruvananthapuram',
    designation: 'Financial Advisor',
    city: 'Thiruvananthapuram',
    state: 'Kerala',
    services: ['MSME Loans', 'IT Startup Advisory', 'Coir Industry Loans', 'Working Capital', 'Kerala State Schemes'],
    phone: '+91-9876543250',
    email: 'rajan@nairfinancial.in',
    bio: 'Trivandrum-based advisor specializing in IT startups and traditional industries. Expert in Technopark and KINFRA benefits.',
    experience: 11,
    reviewCount: 67,
    rating: 4.6,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Additional cities for better coverage

  // Mysore - Karnataka
  {
    name: 'Prashanth Gowda',
    firmName: 'Gowda & Co CA',
    slug: 'gowda-co-ca-mysore',
    designation: 'Chartered Accountant',
    city: 'Mysore',
    state: 'Karnataka',
    services: ['MSME Registration', 'Silk Industry Loans', 'Tax Services', 'Business Advisory', 'Karnataka Schemes'],
    phone: '+91-9876543251',
    email: 'prashanth@gowdaca.com',
    bio: 'Mysore-based CA firm with expertise in silk and traditional industries. Specialized in Karnataka state MSME incentives.',
    experience: 12,
    reviewCount: 67,
    rating: 4.6,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },

  // Rajkot - Gujarat
  {
    name: 'Hitesh Kothari',
    firmName: 'Kothari Business Advisors',
    slug: 'kothari-business-advisors-rajkot',
    designation: 'Business Consultant',
    city: 'Rajkot',
    state: 'Gujarat',
    services: ['MSME Loans', 'Engineering Industry Advisory', 'Working Capital', 'Gujarat Incentives', 'GST Services'],
    phone: '+91-9876543252',
    email: 'hitesh@kothariadvisors.in',
    bio: 'Rajkot-based consultant specializing in engineering and auto parts MSMEs. Expert in Gujarat state capital subsidies.',
    experience: 10,
    reviewCount: 56,
    rating: 4.5,
    isPremium: false,
    tier: 'featured',
    isVerified: true,
  },

  // Ludhiana - Punjab
  {
    name: 'Harpreet Kaur',
    firmName: 'Kaur Financial Services',
    slug: 'kaur-financial-services-ludhiana',
    designation: 'Financial Advisor',
    city: 'Ludhiana',
    state: 'Punjab',
    services: ['MSME Loans', 'Hosiery Industry Advisory', 'Working Capital', 'Punjab Schemes', 'Business Registration'],
    phone: '+91-9876543253',
    email: 'harpreet@kaurfinancial.in',
    bio: 'Ludhiana-based advisor specializing in hosiery, textile, and bicycle MSMEs. Expert in Punjab Industrial Policy benefits.',
    experience: 13,
    reviewCount: 89,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Kanpur - Uttar Pradesh
  {
    name: 'Alok Tiwari',
    firmName: 'Tiwari & Associates CA',
    slug: 'tiwari-associates-ca-kanpur',
    designation: 'Chartered Accountant',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    services: ['MSME Registration', 'Leather Industry Loans', 'Tax Audit', 'UP State Schemes', 'Export Advisory'],
    phone: '+91-9876543254',
    email: 'alok@tiwarica.com',
    bio: 'Kanpur-based CA firm with expertise in leather and footwear MSMEs. Specialized in UP ODOP scheme for leather cluster.',
    experience: 15,
    reviewCount: 112,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Nashik - Maharashtra
  {
    name: 'Sachin Wagh',
    firmName: 'Wagh Business Solutions',
    slug: 'wagh-business-solutions-nashik',
    designation: 'Business Consultant',
    city: 'Nashik',
    state: 'Maharashtra',
    services: ['MSME Loans', 'Wine Industry Advisory', 'Agro Processing', 'Maharashtra Schemes', 'GST Services'],
    phone: '+91-9876543255',
    email: 'sachin@waghsolutions.in',
    bio: 'Nashik-based consultant specializing in wine, grape, and agro-processing MSMEs. Expert in Maharashtra state incentives.',
    experience: 9,
    reviewCount: 45,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },

  // Raipur - Chhattisgarh
  {
    name: 'Manish Agrawal',
    firmName: 'Agrawal Tax Consultants',
    slug: 'agrawal-tax-consultants-raipur',
    designation: 'Tax Consultant',
    city: 'Raipur',
    state: 'Chhattisgarh',
    services: ['MSME Registration', 'Steel Industry Loans', 'Tax Planning', 'CG State Schemes', 'Business Advisory'],
    phone: '+91-9876543256',
    email: 'manish@agrawaltax.in',
    bio: 'Raipur-based consultant with expertise in steel and rice milling MSMEs. Specialized in Chhattisgarh Industrial Policy benefits.',
    experience: 11,
    reviewCount: 56,
    rating: 4.6,
    isPremium: true,
    tier: 'featured',
    isVerified: true,
  },
]

async function main() {
  try {
    console.log('🚀 Starting comprehensive consultants seeding...')
    await prisma.$connect()
    console.log('✅ Database connected')
    console.log('')

    console.log('👨‍💼 Seeding Consultants & CA Firms...')
    let seeded = 0
    let skipped = 0

    for (const consultant of CONSULTANTS) {
      try {
        const existingBySlug = await prisma.consultant.findUnique({
          where: { slug: consultant.slug }
        })

        const existingByEmail = await prisma.consultant.findUnique({
          where: { email: consultant.email }
        })

        if (!existingBySlug && !existingByEmail) {
          await prisma.consultant.create({ data: consultant })
          console.log(`    ✅ Seeded: ${consultant.firmName} - ${consultant.city}, ${consultant.state}`)
          seeded++
        } else {
          console.log(`    ⏭️  Skipped (exists): ${consultant.firmName} - ${consultant.city}`)
          skipped++
        }
      } catch (error) {
        console.error(`    ❌ Error seeding ${consultant.firmName}:`, error)
      }
    }

    console.log('')
    console.log('🎉 Consultants seeding completed!')
    console.log(`📊 Stats:`)
    console.log(`    - Total in seed data: ${CONSULTANTS.length}`)
    console.log(`    - Newly seeded: ${seeded}`)
    console.log(`    - Skipped (existing): ${skipped}`)

    // Get city-wise count
    const cityCount = await prisma.consultant.groupBy({
      by: ['city'],
      _count: { id: true },
      orderBy: { _count: { id: 'desc' } }
    })

    console.log('')
    console.log('🏙️ Consultants by City:')
    for (const city of cityCount) {
      console.log(`    - ${city.city}: ${city._count.id} consultants`)
    }

  } catch (error) {
    console.error('❌ Seeding failed:', error)
    process.exit(1)
  } finally {
    await prisma.$disconnect()
  }
}

main()
