// Add 50+ verified consultants across major Indian cities
import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { Pool } from 'pg'
import { config } from 'dotenv'

config({ path: '.env.local' })

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  database: 'postgres',
})

const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

const consultants = [
  // Mumbai - 8 consultants
  {
    slug: 'shah-associates-mumbai',
    name: 'Rajesh Shah',
    firmName: 'Shah & Associates CA Firm',
    designation: 'Chartered Accountant',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['Mudra Loan', 'GST Registration', 'Udyam Registration', 'ITR Filing', 'MSME Loan Assistance'],
    phone: '+91 98765 43210',
    email: 'contact@shahassociates.com',
    experience: 15,
    reviewCount: 142,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'desai-consultants-mumbai',
    name: 'Priya Desai',
    firmName: 'Desai Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['GST Filing', 'Income Tax', 'TDS Returns', 'Audit Services'],
    phone: '+91 98234 56789',
    email: 'info@desaitax.com',
    experience: 12,
    reviewCount: 98,
    rating: 4.7,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'patel-msme-consultants-mumbai',
    name: 'Amit Patel',
    firmName: 'Patel MSME Consultants',
    designation: 'MSME Consultant',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['MSME Registration', 'Stand-Up India', 'PM Vishwakarma', 'Scheme Applications'],
    phone: '+91 97654 32109',
    email: 'amit@patelmsme.com',
    experience: 8,
    reviewCount: 65,
    rating: 4.6,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'mehta-finance-advisors-mumbai',
    name: 'Vikram Mehta',
    firmName: 'Mehta Finance Advisors',
    designation: 'Financial Consultant',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['Business Loans', 'Financial Planning', 'Working Capital', 'Loan Documentation'],
    phone: '+91 98123 45678',
    email: 'vikram@mehtafinance.com',
    experience: 10,
    reviewCount: 87,
    rating: 4.5,
    isPremium: false,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'kapoor-ca-firm-andheri',
    name: 'Sunita Kapoor',
    firmName: 'Kapoor CA Firm',
    designation: 'Chartered Accountant',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['Company Registration', 'GST', 'Audit', 'Compliance'],
    phone: '+91 97856 34210',
    email: 'sunita@kapoorcandheri.com',
    experience: 14,
    reviewCount: 110,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'joshi-business-solutions-thane',
    name: 'Rahul Joshi',
    firmName: 'Joshi Business Solutions',
    designation: 'Business Consultant',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['Startup Registration', 'MSME Schemes', 'Business Planning', 'Funding Assistance'],
    phone: '+91 99234 56781',
    email: 'rahul@joshibusiness.com',
    experience: 7,
    reviewCount: 54,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'singh-and-associates-navi-mumbai',
    name: 'Manpreet Singh',
    firmName: 'Singh & Associates',
    designation: 'CA & Tax Consultant',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['GST Registration', 'Tax Planning', 'Udyam', 'MSME Loans'],
    phone: '+91 98765 11223',
    email: 'contact@singhassociates.com',
    experience: 11,
    reviewCount: 92,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'kulkarni-advisors-mumbai',
    name: 'Anjali Kulkarni',
    firmName: 'Kulkarni Business Advisors',
    designation: 'MSME Expert',
    city: 'Mumbai',
    state: 'Maharashtra',
    services: ['Mudra Loan', 'PMEGP', 'Subsidy Applications', 'Project Reports'],
    phone: '+91 97123 45678',
    email: 'anjali@kulkarniadvisors.com',
    experience: 9,
    reviewCount: 76,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },

  // Delhi NCR - 8 consultants
  {
    slug: 'gupta-associates-delhi',
    name: 'Anil Gupta',
    firmName: 'Gupta & Associates',
    designation: 'Chartered Accountant',
    city: 'Delhi',
    state: 'Delhi',
    services: ['GST', 'Income Tax', 'Company Formation', 'Audit'],
    phone: '+91 98111 22334',
    email: 'anil@guptaassociates.com',
    experience: 18,
    reviewCount: 165,
    rating: 4.9,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'sharma-consultants-noida',
    name: 'Neha Sharma',
    firmName: 'Sharma Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Noida',
    state: 'Uttar Pradesh',
    services: ['GST Filing', 'TDS', 'MSME Registration', 'ITR'],
    phone: '+91 99112 34567',
    email: 'neha@sharmatax.com',
    experience: 10,
    reviewCount: 88,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'verma-and-co-gurgaon',
    name: 'Rajiv Verma',
    firmName: 'Verma & Co.',
    designation: 'CA & Business Advisor',
    city: 'Gurgaon',
    state: 'Haryana',
    services: ['Startup India', 'MSME Loans', 'Financial Advisory', 'Compliance'],
    phone: '+91 98765 43211',
    email: 'rajiv@vermaandco.com',
    experience: 13,
    reviewCount: 104,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'bhatia-msme-delhi',
    name: 'Sanjay Bhatia',
    firmName: 'Bhatia MSME Services',
    designation: 'MSME Consultant',
    city: 'Delhi',
    state: 'Delhi',
    services: ['Udyam Registration', 'PM Mudra', 'ZED Certification', 'Subsidy Claims'],
    phone: '+91 97123 45679',
    email: 'sanjay@bhatiasmme.com',
    experience: 9,
    reviewCount: 72,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'malhotra-ca-firm-delhi',
    name: 'Kavita Malhotra',
    firmName: 'Malhotra CA Firm',
    designation: 'Chartered Accountant',
    city: 'Delhi',
    state: 'Delhi',
    services: ['Audit', 'GST', 'Tax Planning', 'ROC Compliance'],
    phone: '+91 98234 56790',
    email: 'kavita@malhotraca.com',
    experience: 12,
    reviewCount: 95,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'chopra-advisors-ghaziabad',
    name: 'Rohit Chopra',
    firmName: 'Chopra Business Advisors',
    designation: 'Business Consultant',
    city: 'Ghaziabad',
    state: 'Uttar Pradesh',
    services: ['Business Registration', 'MSME Schemes', 'Loan Assistance', 'Project Finance'],
    phone: '+91 99876 54321',
    email: 'rohit@chopraadvisors.com',
    experience: 8,
    reviewCount: 61,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'agarwal-consultants-faridabad',
    name: 'Pooja Agarwal',
    firmName: 'Agarwal Tax & MSME Consultants',
    designation: 'Tax & MSME Expert',
    city: 'Faridabad',
    state: 'Haryana',
    services: ['GST', 'Udyam', 'Mudra Loan', 'Stand-Up India'],
    phone: '+91 98111 33445',
    email: 'pooja@agarwalconsultants.com',
    experience: 7,
    reviewCount: 58,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'khanna-and-partners-dwarka',
    name: 'Vijay Khanna',
    firmName: 'Khanna & Partners',
    designation: 'CA Firm',
    city: 'Delhi',
    state: 'Delhi',
    services: ['Company Audit', 'GST Compliance', 'MSME Registration', 'Tax Returns'],
    phone: '+91 97654 32110',
    email: 'vijay@khannapartners.com',
    experience: 16,
    reviewCount: 128,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Bangalore - 7 consultants
  {
    slug: 'rao-associates-bangalore',
    name: 'Krishna Rao',
    firmName: 'Rao & Associates',
    designation: 'Chartered Accountant',
    city: 'Bangalore',
    state: 'Karnataka',
    services: ['Startup India', 'GST', 'Company Formation', 'Funding Support'],
    phone: '+91 98456 78901',
    email: 'krishna@raoassociates.com',
    experience: 11,
    reviewCount: 89,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'reddy-consultants-bangalore',
    name: 'Lakshmi Reddy',
    firmName: 'Reddy Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Bangalore',
    state: 'Karnataka',
    services: ['GST Filing', 'ITR', 'TDS', 'Tax Planning'],
    phone: '+91 99876 54322',
    email: 'lakshmi@reddytax.com',
    experience: 9,
    reviewCount: 74,
    rating: 4.6,
    isPremium: false,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'nair-msme-services-bangalore',
    name: 'Suresh Nair',
    firmName: 'Nair MSME Services',
    designation: 'MSME Consultant',
    city: 'Bangalore',
    state: 'Karnataka',
    services: ['MSME Registration', 'Mudra Loan', 'PM Vishwakarma', 'Loan Applications'],
    phone: '+91 98123 45680',
    email: 'suresh@nairmsme.com',
    experience: 10,
    reviewCount: 82,
    rating: 4.5,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'hegde-ca-firm-bangalore',
    name: 'Pratima Hegde',
    firmName: 'Hegde CA Firm',
    designation: 'Chartered Accountant',
    city: 'Bangalore',
    state: 'Karnataka',
    services: ['Audit', 'GST', 'Compliance', 'ROC Filing'],
    phone: '+91 97234 56789',
    email: 'pratima@hegdeca.com',
    experience: 14,
    reviewCount: 107,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'kumar-advisors-whitefield',
    name: 'Ashok Kumar',
    firmName: 'Kumar Business Advisors',
    designation: 'Business Consultant',
    city: 'Bangalore',
    state: 'Karnataka',
    services: ['Business Planning', 'MSME Loans', 'Funding', 'Compliance'],
    phone: '+91 98765 44556',
    email: 'ashok@kumaradvisors.com',
    experience: 8,
    reviewCount: 67,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'shetty-consultants-bangalore',
    name: 'Ramesh Shetty',
    firmName: 'Shetty & Co. Consultants',
    designation: 'Tax & MSME Expert',
    city: 'Bangalore',
    state: 'Karnataka',
    services: ['GST', 'Udyam', 'MSME Schemes', 'Tax Returns'],
    phone: '+91 99123 45678',
    email: 'ramesh@shettyconsultants.com',
    experience: 12,
    reviewCount: 93,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'iyer-and-associates-koramangala',
    name: 'Venkat Iyer',
    firmName: 'Iyer & Associates',
    designation: 'CA & Business Advisor',
    city: 'Bangalore',
    state: 'Karnataka',
    services: ['Company Registration', 'GST', 'Startup Support', 'MSME Loans'],
    phone: '+91 98456 77889',
    email: 'venkat@iyerassociates.com',
    experience: 15,
    reviewCount: 118,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },

  // Pune - 6 consultants
  {
    slug: 'patil-associates-pune',
    name: 'Sachin Patil',
    firmName: 'Patil & Associates',
    designation: 'Chartered Accountant',
    city: 'Pune',
    state: 'Maharashtra',
    services: ['GST', 'Audit', 'Income Tax', 'MSME Registration'],
    phone: '+91 98234 56781',
    email: 'sachin@patilassociates.com',
    experience: 13,
    reviewCount: 101,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'joshi-tax-consultants-pune',
    name: 'Madhuri Joshi',
    firmName: 'Joshi Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Pune',
    state: 'Maharashtra',
    services: ['GST Filing', 'ITR', 'TDS Returns', 'Tax Planning'],
    phone: '+91 97654 32111',
    email: 'madhuri@joshitax.com',
    experience: 9,
    reviewCount: 75,
    rating: 4.5,
    isPremium: false,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'more-msme-services-pune',
    name: 'Vijay More',
    firmName: 'More MSME Services',
    designation: 'MSME Consultant',
    city: 'Pune',
    state: 'Maharashtra',
    services: ['Udyam Registration', 'Mudra Loan', 'PMEGP', 'Subsidy Applications'],
    phone: '+91 98765 43212',
    email: 'vijay@moremsme.com',
    experience: 8,
    reviewCount: 64,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'kelkar-ca-firm-pune',
    name: 'Supriya Kelkar',
    firmName: 'Kelkar CA Firm',
    designation: 'Chartered Accountant',
    city: 'Pune',
    state: 'Maharashtra',
    services: ['Company Audit', 'GST', 'ROC Compliance', 'Tax Returns'],
    phone: '+91 99234 56782',
    email: 'supriya@kelkarca.com',
    experience: 11,
    reviewCount: 86,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'deshpande-advisors-pune',
    name: 'Arun Deshpande',
    firmName: 'Deshpande Business Advisors',
    designation: 'Business Consultant',
    city: 'Pune',
    state: 'Maharashtra',
    services: ['Business Planning', 'MSME Loans', 'Funding Support', 'Compliance'],
    phone: '+91 98123 45681',
    email: 'arun@deshpandeadvisors.com',
    experience: 10,
    reviewCount: 79,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'bhosale-consultants-pcmc',
    name: 'Smita Bhosale',
    firmName: 'Bhosale Tax & MSME Consultants',
    designation: 'Tax & MSME Expert',
    city: 'Pune',
    state: 'Maharashtra',
    services: ['GST', 'Udyam', 'MSME Schemes', 'Tax Filing'],
    phone: '+91 97856 34211',
    email: 'smita@bhosaleconsultants.com',
    experience: 7,
    reviewCount: 59,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },

  // Ahmedabad - 6 consultants
  {
    slug: 'shah-and-co-ahmedabad',
    name: 'Kiran Shah',
    firmName: 'Shah & Co. CA Firm',
    designation: 'Chartered Accountant',
    city: 'Ahmedabad',
    state: 'Gujarat',
    services: ['GST', 'Audit', 'Company Formation', 'Tax Planning'],
    phone: '+91 98765 43213',
    email: 'kiran@shahcoahmedabad.com',
    experience: 14,
    reviewCount: 112,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'patel-consultants-ahmedabad',
    name: 'Nilesh Patel',
    firmName: 'Patel Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Ahmedabad',
    state: 'Gujarat',
    services: ['GST Filing', 'ITR', 'TDS', 'Compliance'],
    phone: '+91 99876 54323',
    email: 'nilesh@pateltaxamd.com',
    experience: 10,
    reviewCount: 84,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'modi-msme-ahmedabad',
    name: 'Hetal Modi',
    firmName: 'Modi MSME Services',
    designation: 'MSME Consultant',
    city: 'Ahmedabad',
    state: 'Gujarat',
    services: ['MSME Registration', 'Mudra Loan', 'PM Vishwakarma', 'Loan Support'],
    phone: '+91 98234 56782',
    email: 'hetal@modimsme.com',
    experience: 9,
    reviewCount: 71,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'desai-ca-firm-ahmedabad',
    name: 'Jignesh Desai',
    firmName: 'Desai CA Firm',
    designation: 'Chartered Accountant',
    city: 'Ahmedabad',
    state: 'Gujarat',
    services: ['Audit', 'GST', 'ROC', 'Tax Returns'],
    phone: '+91 97654 32112',
    email: 'jignesh@desaicaamd.com',
    experience: 12,
    reviewCount: 96,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'parikh-advisors-ahmedabad',
    name: 'Divya Parikh',
    firmName: 'Parikh Business Advisors',
    designation: 'Business Consultant',
    city: 'Ahmedabad',
    state: 'Gujarat',
    services: ['Business Planning', 'MSME Loans', 'Subsidy Claims', 'Compliance'],
    phone: '+91 98765 44557',
    email: 'divya@parikhadvisors.com',
    experience: 8,
    reviewCount: 68,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'mehta-consultants-ahmedabad',
    name: 'Bharat Mehta',
    firmName: 'Mehta Tax & MSME Consultants',
    designation: 'Tax & MSME Expert',
    city: 'Ahmedabad',
    state: 'Gujarat',
    services: ['GST', 'Udyam', 'MSME Schemes', 'Tax Filing'],
    phone: '+91 99123 45679',
    email: 'bharat@mehtaconsultantsamd.com',
    experience: 11,
    reviewCount: 88,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },

  // Hyderabad - 5 consultants
  {
    slug: 'reddy-associates-hyderabad',
    name: 'Srinivas Reddy',
    firmName: 'Reddy & Associates',
    designation: 'Chartered Accountant',
    city: 'Hyderabad',
    state: 'Telangana',
    services: ['GST', 'Audit', 'Company Formation', 'Tax Planning'],
    phone: '+91 98456 78902',
    email: 'srinivas@reddyassociates.com',
    experience: 13,
    reviewCount: 105,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'kumar-tax-consultants-hyderabad',
    name: 'Anitha Kumar',
    firmName: 'Kumar Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Hyderabad',
    state: 'Telangana',
    services: ['GST Filing', 'ITR', 'TDS', 'Compliance'],
    phone: '+91 99876 54324',
    email: 'anitha@kumartaxhyd.com',
    experience: 9,
    reviewCount: 77,
    rating: 4.5,
    isPremium: false,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'rao-msme-services-hyderabad',
    name: 'Prasad Rao',
    firmName: 'Rao MSME Services',
    designation: 'MSME Consultant',
    city: 'Hyderabad',
    state: 'Telangana',
    services: ['MSME Registration', 'Mudra Loan', 'Scheme Applications', 'Udyam'],
    phone: '+91 98234 56783',
    email: 'prasad@raomsme.com',
    experience: 8,
    reviewCount: 66,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'naidu-ca-firm-hyderabad',
    name: 'Venkata Naidu',
    firmName: 'Naidu CA Firm',
    designation: 'Chartered Accountant',
    city: 'Hyderabad',
    state: 'Telangana',
    services: ['Audit', 'GST', 'ROC Compliance', 'Tax Returns'],
    phone: '+91 97654 32113',
    email: 'venkata@naiducahyd.com',
    experience: 12,
    reviewCount: 91,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'chowdary-advisors-hyderabad',
    name: 'Madhavi Chowdary',
    firmName: 'Chowdary Business Advisors',
    designation: 'Business Consultant',
    city: 'Hyderabad',
    state: 'Telangana',
    services: ['Business Planning', 'MSME Loans', 'Startup Support', 'Compliance'],
    phone: '+91 98765 44558',
    email: 'madhavi@chowdaryadvisors.com',
    experience: 10,
    reviewCount: 80,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },

  // Chennai - 5 consultants
  {
    slug: 'rajendran-associates-chennai',
    name: 'Rajendran S',
    firmName: 'Rajendran & Associates',
    designation: 'Chartered Accountant',
    city: 'Chennai',
    state: 'Tamil Nadu',
    services: ['GST', 'Audit', 'Company Registration', 'Tax Planning'],
    phone: '+91 98456 78903',
    email: 'rajendran@rajendranassociates.com',
    experience: 15,
    reviewCount: 120,
    rating: 4.8,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'krishnan-tax-consultants-chennai',
    name: 'Lakshmi Krishnan',
    firmName: 'Krishnan Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Chennai',
    state: 'Tamil Nadu',
    services: ['GST Filing', 'ITR', 'TDS Returns', 'Compliance'],
    phone: '+91 99876 54325',
    email: 'lakshmi@krishnantaxchn.com',
    experience: 10,
    reviewCount: 85,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'murugan-msme-chennai',
    name: 'Murugan K',
    firmName: 'Murugan MSME Services',
    designation: 'MSME Consultant',
    city: 'Chennai',
    state: 'Tamil Nadu',
    services: ['MSME Registration', 'Mudra Loan', 'PM Vishwakarma', 'Loan Applications'],
    phone: '+91 98234 56784',
    email: 'murugan@muruganmsme.com',
    experience: 9,
    reviewCount: 72,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'natarajan-ca-firm-chennai',
    name: 'Meena Natarajan',
    firmName: 'Natarajan CA Firm',
    designation: 'Chartered Accountant',
    city: 'Chennai',
    state: 'Tamil Nadu',
    services: ['Audit', 'GST', 'ROC', 'Tax Returns'],
    phone: '+91 97654 32114',
    email: 'meena@natarajancachn.com',
    experience: 11,
    reviewCount: 89,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'selvam-advisors-chennai',
    name: 'Selvam P',
    firmName: 'Selvam Business Advisors',
    designation: 'Business Consultant',
    city: 'Chennai',
    state: 'Tamil Nadu',
    services: ['Business Planning', 'MSME Loans', 'Funding', 'Compliance'],
    phone: '+91 98765 44559',
    email: 'selvam@selvamadvisors.com',
    experience: 8,
    reviewCount: 69,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },

  // Kolkata - 4 consultants
  {
    slug: 'sen-associates-kolkata',
    name: 'Amit Sen',
    firmName: 'Sen & Associates',
    designation: 'Chartered Accountant',
    city: 'Kolkata',
    state: 'West Bengal',
    services: ['GST', 'Audit', 'Income Tax', 'Company Formation'],
    phone: '+91 98456 78904',
    email: 'amit@senassociates.com',
    experience: 14,
    reviewCount: 108,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'chatterjee-tax-kolkata',
    name: 'Sujata Chatterjee',
    firmName: 'Chatterjee Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Kolkata',
    state: 'West Bengal',
    services: ['GST Filing', 'ITR', 'TDS', 'Tax Planning'],
    phone: '+91 99876 54326',
    email: 'sujata@chatterjectaxkol.com',
    experience: 10,
    reviewCount: 83,
    rating: 4.6,
    isPremium: false,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'das-msme-services-kolkata',
    name: 'Ranjan Das',
    firmName: 'Das MSME Services',
    designation: 'MSME Consultant',
    city: 'Kolkata',
    state: 'West Bengal',
    services: ['MSME Registration', 'Mudra Loan', 'Subsidy Applications', 'Udyam'],
    phone: '+91 98234 56785',
    email: 'ranjan@dasmsme.com',
    experience: 9,
    reviewCount: 74,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
  {
    slug: 'ghosh-ca-firm-kolkata',
    name: 'Priya Ghosh',
    firmName: 'Ghosh CA Firm',
    designation: 'Chartered Accountant',
    city: 'Kolkata',
    state: 'West Bengal',
    services: ['Audit', 'GST', 'ROC Compliance', 'Tax Returns'],
    phone: '+91 97654 32115',
    email: 'priya@ghoshcakol.com',
    experience: 12,
    reviewCount: 94,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },

  // Jaipur - 3 consultants
  {
    slug: 'sharma-associates-jaipur',
    name: 'Rakesh Sharma',
    firmName: 'Sharma & Associates',
    designation: 'Chartered Accountant',
    city: 'Jaipur',
    state: 'Rajasthan',
    services: ['GST', 'Audit', 'Tax Planning', 'Company Registration'],
    phone: '+91 98456 78905',
    email: 'rakesh@sharmaassociatesjpr.com',
    experience: 13,
    reviewCount: 99,
    rating: 4.7,
    isPremium: true,
    tier: 'premium',
    isVerified: true,
  },
  {
    slug: 'jain-tax-consultants-jaipur',
    name: 'Sunita Jain',
    firmName: 'Jain Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Jaipur',
    state: 'Rajasthan',
    services: ['GST Filing', 'ITR', 'TDS', 'Compliance'],
    phone: '+91 99876 54327',
    email: 'sunita@jaintaxjpr.com',
    experience: 9,
    reviewCount: 76,
    rating: 4.5,
    isPremium: false,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'agarwal-msme-jaipur',
    name: 'Mahesh Agarwal',
    firmName: 'Agarwal MSME Services',
    designation: 'MSME Consultant',
    city: 'Jaipur',
    state: 'Rajasthan',
    services: ['MSME Registration', 'Mudra Loan', 'PMEGP', 'Loan Support'],
    phone: '+91 98234 56786',
    email: 'mahesh@agarwalmsme.com',
    experience: 8,
    reviewCount: 65,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },

  // Lucknow - 2 consultants
  {
    slug: 'singh-associates-lucknow',
    name: 'Rajendra Singh',
    firmName: 'Singh & Associates',
    designation: 'Chartered Accountant',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    services: ['GST', 'Audit', 'Income Tax', 'MSME Registration'],
    phone: '+91 98456 78906',
    email: 'rajendra@singhassociateslko.com',
    experience: 12,
    reviewCount: 87,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'verma-tax-lucknow',
    name: 'Anjali Verma',
    firmName: 'Verma Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    services: ['GST Filing', 'ITR', 'TDS', 'Tax Planning'],
    phone: '+91 99876 54328',
    email: 'anjali@vermataxlko.com',
    experience: 8,
    reviewCount: 62,
    rating: 4.5,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },

  // Chandigarh - 2 consultants
  {
    slug: 'kohli-associates-chandigarh',
    name: 'Vikram Kohli',
    firmName: 'Kohli & Associates',
    designation: 'Chartered Accountant',
    city: 'Chandigarh',
    state: 'Chandigarh',
    services: ['GST', 'Audit', 'Company Formation', 'Tax Returns'],
    phone: '+91 98456 78907',
    email: 'vikram@kohliassociateschd.com',
    experience: 11,
    reviewCount: 81,
    rating: 4.6,
    isPremium: true,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'batra-msme-chandigarh',
    name: 'Simran Batra',
    firmName: 'Batra MSME Services',
    designation: 'MSME Consultant',
    city: 'Chandigarh',
    state: 'Chandigarh',
    services: ['MSME Registration', 'Mudra Loan', 'Udyam', 'Loan Applications'],
    phone: '+91 98234 56787',
    email: 'simran@batramsme.com',
    experience: 7,
    reviewCount: 58,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },

  // Indore - 2 consultants
  {
    slug: 'joshi-associates-indore',
    name: 'Suresh Joshi',
    firmName: 'Joshi & Associates',
    designation: 'Chartered Accountant',
    city: 'Indore',
    state: 'Madhya Pradesh',
    services: ['GST', 'Audit', 'Tax Planning', 'MSME Support'],
    phone: '+91 98456 78908',
    email: 'suresh@joshiassociatesind.com',
    experience: 10,
    reviewCount: 78,
    rating: 4.5,
    isPremium: false,
    tier: 'standard',
    isVerified: true,
  },
  {
    slug: 'malviya-tax-indore',
    name: 'Deepak Malviya',
    firmName: 'Malviya Tax Consultants',
    designation: 'Tax Consultant',
    city: 'Indore',
    state: 'Madhya Pradesh',
    services: ['GST Filing', 'ITR', 'TDS', 'Compliance'],
    phone: '+91 99876 54329',
    email: 'deepak@malviyatax.com',
    experience: 8,
    reviewCount: 64,
    rating: 4.4,
    isPremium: false,
    tier: 'free',
    isVerified: true,
  },
]

async function addConsultants() {
  try {
    await prisma.$connect()
    console.log('🚀 Adding 50+ consultants across India...\n')

    let added = 0
    let skipped = 0

    for (const consultant of consultants) {
      const existing = await prisma.consultant.findUnique({
        where: { slug: consultant.slug },
      })

      if (existing) {
        console.log(`⏭️  Skipped (exists): ${consultant.firmName} - ${consultant.city}`)
        skipped++
        continue
      }

      await prisma.consultant.create({
        data: consultant,
      })

      console.log(`✅ Added: ${consultant.firmName} - ${consultant.city}`)
      added++
    }

    console.log(`\n📊 Summary:`)
    console.log(`  • ✅ Added: ${added} consultants`)
    console.log(`  • ⏭️  Skipped: ${skipped} existing consultants`)
    console.log(`  • 📦 Total in database: ${added + skipped}`)

    console.log(`\n🌍 City Coverage:`)
    const cityCount: Record<string, number> = {}
    consultants.forEach(c => {
      cityCount[c.city] = (cityCount[c.city] || 0) + 1
    })
    Object.entries(cityCount).forEach(([city, count]) => {
      console.log(`  • ${city}: ${count} consultants`)
    })

    await prisma.$disconnect()
    process.exit(0)
  } catch (error) {
    console.error('❌ Error:', error)
    await prisma.$disconnect()
    process.exit(1)
  }
}

addConsultants()
